### PR TITLE
Fix Condition check for Reconcile InstallPlan status

### LINKED ISSUE #3151: [Flake] End-to-end.[It] Subscription can reconcile InstallPlan status
## Flaky Test Report

With TestGrid behaving better, this seems to be a consistent flake.

**Failure Log Link**
[Failure Log](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-operator-framework-olm-master-periodics-e2e-gcp-olm/1745053030421630976)
You can get the link by clicking on the line number in the job logs and copying the url from your browser.

**Relevant Failure Log**

```
------------------------------
Subscription can reconcile InstallPlan status
/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1031
  created the subscription-e2e-x7zng testing namespace
  created the subscription-e2e-x7zng/subscription-e2e-x7zng-operatorgroup operator group
  STEP: TestSubscriptionInstallPlanStatus ensures that a Subscription has the appropriate status conditions for possible referenced @ 01/10/24 13:21:44.294
  STEP: InstallPlan states. @ 01/10/24 13:21:44.295
  STEP: 	BySteps: @ 01/10/24 13:21:44.295
  STEP: - Utilize the namespace and OG targeting that namespace created in the BeforeEach clause @ 01/10/24 13:21:44.295
  STEP: - Create CatalogSource, cs, in ns @ 01/10/24 13:21:44.296
  STEP: - Create Subscription to a package of cs in ns, sub @ 01/10/24 13:21:44.296
  STEP: - Wait for the package from sub to install successfully with no remaining InstallPlan status conditions @ 01/10/24 13:21:44.296
  STEP: - Store conditions for later comparision @ 01/10/24 13:21:44.296
  STEP: - Get the InstallPlan @ 01/10/24 13:21:44.296
  STEP: - Set the InstallPlan's approval mode to Manual @ 01/10/24 13:21:44.296
  STEP: - Set the InstallPlan's phase to None @ 01/10/24 13:21:44.296
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanPending true and reason InstallPlanNotYetReconciled @ 01/10/24 13:21:44.296
  STEP: - Get the latest IntallPlan and set the phase to InstallPlanPhaseRequiresApproval @ 01/10/24 13:21:44.297
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanPending true and reason RequiresApproval @ 01/10/24 13:21:44.297
  STEP: - Get the latest InstallPlan and set the phase to InstallPlanPhaseInstalling @ 01/10/24 13:21:44.297
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanPending true and reason Installing @ 01/10/24 13:21:44.297
  STEP: - Get the latest InstallPlan and set the phase to InstallPlanPhaseFailed and remove all status conditions @ 01/10/24 13:21:44.297
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanFailed true and reason InstallPlanFailed @ 01/10/24 13:21:44.298
  STEP: - Get the latest InstallPlan and set status condition of type Installed to false with reason InstallComponentFailed @ 01/10/24 13:21:44.298
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanFailed true and reason InstallComponentFailed @ 01/10/24 13:21:44.298
  STEP: - Delete the referenced InstallPlan @ 01/10/24 13:21:44.298
  STEP: - Wait for sub to have status condition SubscriptionInstallPlanMissing true @ 01/10/24 13:21:44.298
  STEP: - Ensure original non-InstallPlan status conditions remain after InstallPlan transitions @ 01/10/24 13:21:44.298
  STEP: Create CatalogSource, cs, in ns @ 01/10/24 13:21:44.298
  STEP: set a simple default strategy if none given @ 01/10/24 13:21:44.298
  STEP: Create an nginx details deployment @ 01/10/24 13:21:44.299
  STEP: Populate owned and required @ 01/10/24 13:21:44.299
  Creating catalog source catalog-rhnmc in namespace subscription-e2e-x7zng...
  Catalog source catalog-rhnmc created
waiting 151.262248ms for catalog pod subscription-e2e-x7zng/catalog-rhnmc to be available (for sync) - NO_CONNECTION
waiting 88.767398ms for catalog pod subscription-e2e-x7zng/catalog-rhnmc to be available (for sync) - TRANSIENT_FAILURE
waiting 16.756945756s for catalog pod subscription-e2e-x7zng/catalog-rhnmc to be available (for sync) - READY
probing catalog catalog-rhnmc pod with address catalog-rhnmc.subscription-e2e-x7zng.svc:50051
skipping health check
  STEP: Create Subscription to a package of cs in ns, sub @ 01/10/24 13:22:01.402
  STEP: Wait for the package from sub to install successfully with no remaining InstallPlan status conditions @ 01/10/24 13:22:01.606
  13:22:05.4089: subscription subscription-e2e-x7zng/sub-c7bj2 state: UpgradePending (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  waiting 3.802536879s for subscription subscription-e2e-x7zng/sub-c7bj2 to have state AtLatestKnown: has state UpgradePending
  13:22:06.6027: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  waiting 1.193729775s for subscription subscription-e2e-x7zng/sub-c7bj2 to have state AtLatestKnown: has state AtLatestKnown
  STEP: Store conditions for later comparision @ 01/10/24 13:22:06.602
  STEP: Set the InstallPlan's approval mode to Manual @ 01/10/24 13:22:06.603
  STEP: Set the InstallPlan's phase to None @ 01/10/24 13:22:06.806
  STEP: Wait for sub to have status condition SubscriptionInstallPlanPending true and reason InstallPlanNotYetReconciled @ 01/10/24 13:22:06.992
  13:22:07.1371: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Set the phase to InstallPlanPhaseRequiresApproval @ 01/10/24 13:22:07.604
  STEP: Wait for sub to have status condition SubscriptionInstallPlanPending true and reason RequiresApproval @ 01/10/24 13:22:07.8
  13:22:07.9438: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Set the phase to InstallPlanPhaseInstalling @ 01/10/24 13:22:11.803
  STEP: Wait for sub to have status condition SubscriptionInstallPlanPending true and reason Installing @ 01/10/24 13:22:11.99
  13:22:12.1328: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Sometimes the transition from installing to complete can be so quick that the test does not capture @ 01/10/24 13:22:12.132
  STEP: the condition in the subscription before it is removed. To mitigate this, we check if the installplan @ 01/10/24 13:22:12.133
  STEP: has transitioned to complete and exit out the fetch subscription loop if so. @ 01/10/24 13:22:12.133
  STEP: This is a mitigation. We should probably fix this test appropriately. @ 01/10/24 13:22:12.133
  STEP: issue: https://github.com/operator-framework/operator-lifecycle-manager/issues/2667 @ 01/10/24 13:22:12.133
  STEP: Set the phase to InstallPlanPhaseFailed and remove all status conditions @ 01/10/24 13:22:12.205
  STEP: Wait for sub to have status condition SubscriptionInstallPlanFailed true and reason InstallPlanFailed @ 01/10/24 13:22:12.386
  13:22:12.5297: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Set status condition of type Installed to false with reason InstallComponentFailed @ 01/10/24 13:22:15.203
  STEP: Wait for sub to have status condition SubscriptionInstallPlanFailed true and reason InstallComponentFailed @ 01/10/24 13:22:15.391
  13:22:15.5329: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Delete the referenced InstallPlan @ 01/10/24 13:22:17.204
  STEP: Wait for sub to have status condition SubscriptionInstallPlanMissing true @ 01/10/24 13:22:17.421
  13:22:17.6062: subscription subscription-e2e-x7zng/sub-c7bj2 state: AtLatestKnown (csv pkg-8tn49): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"subscription-e2e-x7zng", Name:"install-ffqv6", UID:"618a580d-9293-43f0-8da5-c4789ff16fba", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"66857", FieldPath:""}
  STEP: Ensure original non-InstallPlan status conditions remain after InstallPlan transitions @ 01/10/24 13:22:19.204
  Cleaning catalog source catalog-rhnmc
  Deleting config map catalog-rhnmc-configmap...
  Deleting catalog source catalog-rhnmc...
  waiting for the catalog source catalog-rhnmc-5gvhl pod to be deleted...
  Done cleaning catalog source catalog-rhnmc
  [FAILED] in [It] - /go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1222 @ 01/10/24 13:22:20.695
  collecting the subscription-e2e-x7zng namespace artifacts as the 'can reconcile InstallPlan status' test case failed
  collecting logs in the /logs/artifacts artifacts directory
  unable to determine kubeconfig path so defaulting to the $KUBECONFIG value
Using the oc kubectl binary
Using the /logs/artifacts/subscription-e2e-x7zng output directory
Storing the test artifact output in the /logs/artifacts/subscription-e2e-x7zng directory
Collecting get catalogsources -o yaml output...
Collecting get subscriptions -o yaml output...
Collecting get operatorgroups -o yaml output...
Collecting get clusterserviceversions -o yaml output...
Collecting get installplans -o yaml output...
Collecting get pods -o wide output...
Collecting get events --sort-by .lastTimestamp output...
  tearing down the subscription-e2e-x7zng namespace
  resetting e2e kube client
  deleting subscription-e2e-x7zng/subscription-e2e-x7zng-operatorgroup
  deleting <global>/subscription-e2e-x7zng
  garbage collecting CRDs
  deleting crd pkg-8tn49.cluster.com
• [FAILED] [40.775 seconds]
Subscription [It] can reconcile InstallPlan status
/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1031
  [FAILED] 
  	Error Trace:	/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1222
  	            				/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
  	            				/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:865
  	            				/usr/lib/golang/src/runtime/asm_amd64.s:1598
  	Error:      	Should be true
  	Test:       	Subscription can reconcile InstallPlan status
  	Messages:   	non-installplan status condition changed
  
  In [It] at: /go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1222 @ 01/10/24 13:22:20.695
  Full Stack Trace
    github.com/stretchr/testify/require.True({0x7f5b61b23bf0, 0xc000fa3170}, 0xc0?, {0xc001f0e890, 0x1, 0x1})
    	/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1918 +0x92
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func26.12()
    	/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1222 +0x23d1
------------------------------
```

### PR DESCRIPTION
**Pull request by tmshort**
Fix #3151

The Reason check for CatalogSourcesUnhealthy does not take into account that CatalogSourcesAdded may overwrite the AllCatalogSourcesHealthy reason because the number of catalog sources changed. So, depending on when reconcilliation happens relative to the catalog sources being added, the initial Reason may be either Added or Healthy.

At the end of the test, also depending on when reconcilliation happens, the new Reason may be Added or Healthy.

* Both could be the same (Added or Healthy)
* Or, the original could be Added and the new could be Healthy

New can't be Added after the original is Healthy because no additional catalog sources are added once the test starts.

However, the Status and Message (which is the real indicator of health) must match. And because of the possible update, don't check the timestamps.

Also:
* Clean up some looping log messages
* Clean up some logging added when comments were converted

These comments/logs are at the beginning of the test, and are also part of the test sequence, so they are redundant (and possibly confusing)

**Description of the change:**

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

File: test/e2e/subscription_e2e_test.go [hunk 1]
```diff
@@ -1218,6 +1197,18 @@ var _ = Describe("Subscription", func() {
...
 			case operatorsv1alpha1.SubscriptionInstallPlanMissing:
 				require.Equal(GinkgoT(), operatorsv1alpha1.ReferencedInstallPlanNotFound, cond.Reason)
+			case operatorsv1alpha1.SubscriptionCatalogSourcesUnhealthy:
+				newCond := sub.Status.GetCondition(condType)
+				require.Equal(GinkgoT(), cond.Status, newCond.Status)
+				require.Equal(GinkgoT(), cond.Message, newCond.Message)
+				// The Reason check:
+				// CatalogSources[Added|Deleted] could overwrite AllCatalogSourcesHealthy, but leave Status/Message preserved
+				// Added/Deleted could subesequently be overwritten by Healthy
+				// This all depends on when reconciliation occurs and if the number of catalog sources changed between reconcilliations
```
Comment (grokspawn) [inline test/e2e/subscription_e2e_test.go:1207]:
```suggestion
				// This all depends on when reconciliation occurs and if the number of catalog sources changed between reconciliations
```

Comment (tmshort) [reply test/e2e/subscription_e2e_test.go:1207]: Ugh... no spell checker in my code editor!

File: test/e2e/subscription_e2e_test.go [hunk 2]
```diff
@@ -3218,27 +3209,47 @@ func subscriptionHasCurrentCSV(currentCSV string) subscriptionStateChecker {
...
 			return true
 		}
 
-		fmt.Printf("subscription condition not met: %v\n", cond)
+		if lastCond.Status != cond.Status && lastCond.Reason != cond.Reason && lastCond.Message == cond.Message {
+			GinkgoT().Logf("waited %s subscription condition not met: %v\n", time.Since(lastTime), cond)
+			lastTime = time.Now()
+			lastCond = cond
+		}
 		return false
```
Comment (grokspawn) [inline test/e2e/subscription_e2e_test.go:3230]: I would love if there were a way to write this for greater readability. 
Maybe a comment something like
```go
// if status/reason/message meet expectations, then subscription state is considered met/true IFF this is the result of a recent change of status/reason
```

Comment (tmshort) [reply test/e2e/subscription_e2e_test.go:3230]: This is the general trend to reduce repetitive logging, and I admit, the comparisons are ugly.

Comment (tmshort) [reply test/e2e/subscription_e2e_test.go:3230]: BUT... that's not the reason for the change... The change reduces the logging when conditions don't change, the reason for getting out of the loop doesn't change, just the output.

File: test/e2e/subscription_e2e_test.go [hunk 3]
```diff
@@ -1218,6 +1197,18 @@ var _ = Describe("Subscription", func() {
 				require.FailNowf(GinkgoT(), "failed", "subscription contains unexpected installplan condition: %v", cond)
 			case operatorsv1alpha1.SubscriptionInstallPlanMissing:
 				require.Equal(GinkgoT(), operatorsv1alpha1.ReferencedInstallPlanNotFound, cond.Reason)
+			case operatorsv1alpha1.SubscriptionCatalogSourcesUnhealthy:
```
Comment (stevekuznetsov) [inline test/e2e/subscription_e2e_test.go:1200]: The way this test is written makes it sensitive to _any_ change in the cluster state or the reconciliation flow of the controller. Since we're trying to test a negative ("all of the non-`InstallPlan` conditions can change between the time we looked at them in the beginning of the test and now"), I don't know that this test is super powerful, and, since that kind of approach is very fragile, I wonder if a different approach exists (maybe just to delete the test? what is it testing?).

Consider the case where a CatalogSource happens to blip unhealthy for a moment during this check. Why should the test fail if the reconciler has correctly exposed that downtime in status?

File: test/e2e/subscription_e2e_test.go [hunk 4]
```diff
@@ -1210,16 +1188,13 @@ var _ = Describe("Subscription", func() {
 		Expect(err).ToNot(HaveOccurred())
 		Expect(sub).ToNot(BeNil())
 
-		By(`Ensure original non-InstallPlan status conditions remain after InstallPlan transitions`)
-		hashEqual := comparison.NewHashEqualitor()
+		By(`Ensure original, specific, non-InstallPlan status conditions remain after InstallPlan transitions`)
```
Comment (stevekuznetsov) [inline test/e2e/subscription_e2e_test.go:1191]:
```suggestion
		By(`Ensure InstallPlan-related status conditions match what we're expecting`)
```

**Review by stevekuznetsov — APPROVED** [review]

**Comment by tmshort** [comment]
That should be including the (new) finalizer code in the merge. AFAICT, it's failing on the delete of the CSV (not on the removal of the CRBs/CRs/SA), as in the original failure.

The merge queue was also failing on unit test, so something was wonky.
