### PR TITLE
Fix e2e Install Plan creation with permission

### LINKED ISSUE #3108: Install Plan creation with permissions
```
 Install Plan creation with permissions
/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2710
  created the install-plan-e2e-vg886 testing namespace
  Creating catalog source nginx-cataloglrblz in namespace install-plan-e2e-vg886...
  Catalog source nginx-cataloglrblz created
waiting 142.077223ms for catalog pod install-plan-e2e-vg886/nginx-cataloglrblz to be available (for sync) - NO_CONNECTION
waiting 98.120985ms for catalog pod install-plan-e2e-vg886/nginx-cataloglrblz to be available (for sync) - TRANSIENT_FAILURE
waiting 15.351299079s for catalog pod install-plan-e2e-vg886/nginx-cataloglrblz to be available (for sync) - READY
probing catalog nginx-cataloglrblz pod with address nginx-cataloglrblz.install-plan-e2e-vg886.svc:50051
skipping health check
  17:50:18.6422: subscription install-plan-e2e-vg886/sub-nginx-lkkkz state: UpgradePending (csv nginx9ld7b-stable): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"install-plan-e2e-vg886", Name:"install-ccrcg", UID:"df84614d-2e1f-47f7-acb5-9c3c15cff097", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"156380", FieldPath:""}
  waiting 803.038045ms for subscription install-plan-e2e-vg886/sub-nginx-lkkkz to have installplan ref: has ref &v1.ObjectReference{Kind:"InstallPlan", Namespace:"install-plan-e2e-vg886", Name:"install-ccrcg", UID:"df84614d-2e1f-47f7-acb5-9c3c15cff097", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"156380", FieldPath:""}
  waiting 197.898463ms for installplan install-plan-e2e-vg886/install-ccrcg to be phases [Failed Complete], in phase Installing
  waiting 4.196911018s for installplan install-plan-e2e-vg886/install-ccrcg to be phases [Failed Complete], in phase Complete
  {nginx9ld7b-stable ClusterServiceVersion }, {nginx9ld7b-stable ClusterRoleBinding }: true && false
  {nginx9ld7b-stable ClusterServiceVersion }, {insqcpnr.cluster.com CustomResourceDefinition }: false && false
  {nginx9ld7b-stable ClusterServiceVersion }, {nginx-sabgxrp ServiceAccount }: false && false
  {nginx9ld7b-stable ClusterServiceVersion }, {nginx9ld7b-stable Role }: true && false
  {nginx9ld7b-stable ClusterServiceVersion }, {nginx9ld7b-stable RoleBinding }: true && false
  {nginx9ld7b-stable ClusterServiceVersion }, {nginx9ld7b-stable ClusterRole }: true && false
  {insqcpnr.cluster.com CustomResourceDefinition }, {nginx9ld7b-stable ClusterRoleBinding }: false && false
  {insqcpnr.cluster.com CustomResourceDefinition }, {nginx-sabgxrp ServiceAccount }: false && false
  {insqcpnr.cluster.com CustomResourceDefinition }, {nginx9ld7b-stable Role }: false && false
  {insqcpnr.cluster.com CustomResourceDefinition }, {nginx9ld7b-stable RoleBinding }: false && false
  {insqcpnr.cluster.com CustomResourceDefinition }, {nginx9ld7b-stable ClusterRole }: false && false
  {nginx-sabgxrp ServiceAccount }, {nginx9ld7b-stable Role }: false && false
  {nginx-sabgxrp ServiceAccount }, {nginx9ld7b-stable RoleBinding }: false && false
  {nginx-sabgxrp ServiceAccount }, {nginx9ld7b-stable ClusterRole }: false && false
  {nginx-sabgxrp ServiceAccount }, {nginx9ld7b-stable ClusterRoleBinding }: false && false
  {nginx9ld7b-stable-nginx-sabgxrp-7c86848fc4 Role }, {nginx9ld7b-stable RoleBinding }: true && false
  {nginx9ld7b-stable-nginx-sabgxrp-7c86848fc4 Role }, {nginx9ld7b-stable ClusterRole }: true && false
  {nginx9ld7b-stable-nginx-sabgxrp-7c86848fc4 Role }, {nginx9ld7b-stable ClusterRoleBinding }: true && false
  {nginx9ld7b-stable-nginx-sabgxrp-7c86848fc4 RoleBinding }, {nginx9ld7b-stable ClusterRole }: true && false
  {nginx9ld7b-stable-nginx-sabgxrp-7c86848fc4 RoleBinding }, {nginx9ld7b-stable ClusterRoleBinding }: true && false
  {nginx9ld7b-stable-747c79bd4f ClusterRole }, {nginx9ld7b-stable ClusterRoleBinding }: true && false
  deleting csv install-plan-e2e-vg886/nginx9ld7b-stable
  Deleting config map nginx-cataloglrblz-configmap...
  Deleting catalog source nginx-cataloglrblz...
  waiting for the catalog source nginx-cataloglrblz-d9qpx pod to be deleted...
  [FAILED] in [It] - /go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2905 @ 11/13/23 18:00:24.687
  collecting the install-plan-e2e-vg886 namespace artifacts as the 'creation with permissions' test case failed
  collecting logs in the /logs/artifacts artifacts directory
  unable to determine kubeconfig path so defaulting to the $KUBECONFIG value
Using the oc kubectl binary
Using the /logs/artifacts/install-plan-e2e-vg886 output directory
Storing the test artifact output in the /logs/artifacts/install-plan-e2e-vg886 directory
Collecting get catalogsources -o yaml output...
Collecting get subscriptions -o yaml output...
Collecting get operatorgroups -o yaml output...
Collecting get clusterserviceversions -o yaml output...
Collecting get installplans -o yaml output...
Collecting get pods -o wide output...
Collecting get events --sort-by .lastTimestamp output...
  tearing down the install-plan-e2e-vg886 namespace
  resetting e2e kube client
  deleting install-plan-e2e-vg886/install-plan-e2e-vg886-operatorgroup
  deleting <global>/install-plan-e2e-vg886
  garbage collecting CRDs
• [FAILED] [627.154 seconds]
Install Plan [It] creation with permissions
/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2710
  [FAILED] Timed out after 600.020s.
  Expected
      <bool>: false
  to be true
  In [It] at: /go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2905 @ 11/13/23 18:00:24.687
  Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func17.13()
    	/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2905 +0x33ca 
```

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_operator-framework-olm/606/pull-ci-openshift-operator-framework-olm-master-e2e-gcp-olm/1724082802661527552

### PR DESCRIPTION
**Pull request by tmshort**
Fix #3108

The Subscription needs to be deleted before deleting the CSV, otherwise the Subscription will recreate the CSV, and subsequently, the CR/CRBs are not deleted.

Update some test logging as well.

Signed-off-by: Todd Short <todd.short@me.com>

**Description of the change:**

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold

Even if this happens to ameliorate the symptom, not adding a finalizer means that the system remains capable of producing incorrect output. I don't suggest that.

**Comment by tmshort** [comment]
@stevekuznetsov:
> Even if this happens to ameliorate the symptom, not adding a finalizer means that the system remains capable of producing incorrect output. I don't suggest that.

I consider the Finalizer/Deletion issue separate from the Install Plan test flake. I'm not ignoring that! I'm not actually 100% sure it's a finalizer issue, as the CSV is not actually removed when deleted; the delete succeeds, but the CSV remains.

I created #3130 to track the Finalizer/Deletion issue. This gets us past the test issue so we can continue to contribute code.

**Comment by stevekuznetsov** [comment]
The only mechanism that exists in Kubernetes to ensure that some action is taken before an object is fully deleted is to use a finalizer. The controller attempts to ensure that a cleanup action is taken, but it cannot do that without using a finalizer. No finalizer is added to the CSV object. I don't think there is room for uncertainty about whether or not "it's a finalizer issue".

**Comment by tmshort** [comment]
Seeing some weird behavior here.
This had been succeeding 100% yesterday.
After getting to the success state, and then deleting, the CSV is going into some other state...

**Comment by tmshort** [comment]
The problem with the test is that the CSV ends up being re-created by the Subscription (I've discovered that the UID on the CSVs are different). According to @awgreene, this test worked previously because of the poor performance. With improved performance, the CSV is being recreated in time for the CR/CRBs to remain (or possibly be re-created, I did not check those UIDs). The Subscription should be deleted before the CSV, to ensure the CSV remains deleted.

This still does not obviate the potential need for a finalizer, however.

File: test/e2e/installplan_e2e_test.go [hunk 1]
```diff
@@ -2867,42 +2870,64 @@ var _ = Describe("Install Plan", func() {
 		By("Should have removed every matching step")
 		require.Equal(GinkgoT(), 0, len(expectedSteps), "Actual resource steps do not match expected: %#v", expectedSteps)
 
-		GinkgoT().Logf("deleting csv %s/%s", generatedNamespace.GetName(), stableCSVName)
-		By("Explicitly delete the CSV")
+		By("Waiting on CSV to succeed before deleting")
+		_, err = fetchCSV(crc, generatedNamespace.GetName(), stableCSVName, csvSucceededChecker)
```
Comment (stevekuznetsov) [inline test/e2e/installplan_e2e_test.go:2874]: Are we going to remove this step?

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go:2874]: Yes.
