### PR TITLE
Bug 1855088: generate unique (Cluster)RoleBinding names

### LINKED ISSUE #1625: OLM doesn't create roles corresponding to the `permissions` defined in the CSV file
## Bug Report

**What did you do?**
We are trying to install IBM IAM Operator(https://github.com/IBM/ibm-iam-operator) from this catalogSource defintion:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: quay.io/opencloudio/ibm-common-service-catalog:dev-latest
  updateStrategy:
    registryPoll:
      interval: 45m
```

The following permissions are defined in our CSV https://github.com/IBM/ibm-iam-operator/blob/master/deploy/olm-catalog/ibm-iam-operator/3.6.4/ibm-iam-operator.v3.6.4.clusterserviceversion.yaml#L1592-L1953 . 

**What did you expect to see?**
We expect to see three different roles to be created and associated with three different serviceAccounts as it is evident from the lines highlighted in the CSV file.

**What did you see instead? Under which circumstances?**
All the three roles and rolebindings to associate them to the serviceAccounts were created successfully prior to Openshift Container Platform 4.4.6 and everything worked as expected. However, we have found that on Openshift Container Platform 4.4.11 and 4.5.0-rc6, all the three roles and rolebindings to the serviceaccounts have NOT been created(only one role and rolebinding is created) and the following errors are seen:
```
oc describe csv ibm-iam-operator | grep NotSatisfied -B 5
      Status:   Satisfied
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["get","create"],"apiGroups":["monitoring.coreos.com"],"resources":["servicemonitors"]}
      Status:   NotSatisfied
--
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["update"],"apiGroups":["apps"],"resources":["deployments/finalizers"],"resourceNames":["ibm-iam-operator"]}
      Status:   NotSatisfied
--
      Status:   Satisfied
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["operator.ibm.com"],"resources":["*","policydecisions","oidcclientwatchers","authentications","policycontrollers","paps","securityonboardings"]}
      Status:   NotSatisfied
--
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["certmanager.k8s.io"],"resources":["*","certificates"]}
      Status:   NotSatisfied
--
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["networking.k8s.io"],"resources":["*","ingresses"]}
      Status:   NotSatisfied
--
      Version:  v1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["batch"],"resources":["jobs"]}
      Status:   NotSatisfied
--
      Version:  v1
    Group:
    Kind:       ServiceAccount
    Message:    Policy rule not satisfied for service account
    Name:       ibm-iam-operand-restricted
    Status:     PresentNotSatisfied
```

**Environment**
* operator-lifecycle-manager version:
OLM version: 0.15.1
git commit: 922f6adf41c7ae7bb9c9a63fdd021cf2cd4dcf2c

* Kubernetes version information:

Kubernetes Version: v1.18.3+6025c28

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by matskiv**
**Description of the change:**
Make ServiceAccount name part of the input for (Cluster)RoleBinding name generation.
This is done by passing `permission` object, of `StrategyDeploymentPermissions` type,
which contains `ServiceAccountName` and `Rules` fields.

**Motivation for the change:**
When same permission rules were defined for different ServiceAccounts,
OLM would generate same name for (Cluster)RoleBinding related to this rules.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1855088
Closes #1625 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by matskiv** [comment]
Note: this PR only addresses (Cluster)RoleBinding that are created when there are identical permissions rules.
OLM will still create just one (Cluster)Role, which will then be bound to multiple ServiceAccounts.
I would call this accidental optimization :)
Not sure if this needs to be addressed or not.

File: pkg/controller/registry/resolver/rbac.go [hunk 1]
```diff
@@ -147,7 +147,7 @@ func RBACForClusterServiceVersion(csv *v1alpha1.ClusterServiceVersion) (map[stri
 		// Create ClusterRoleBinding
 		roleBinding := &rbacv1.ClusterRoleBinding{
 			ObjectMeta: metav1.ObjectMeta{
-				Name:      generateName(role.GetName(), role),
+				Name:      generateName(role.GetName(), permission),
```
Comment (njhale) [inline pkg/controller/registry/resolver/rbac.go:150]: can we still get a collision if the same operator is installed into two different namespaces?

Comment (matskiv) [reply pkg/controller/registry/resolver/rbac.go:150]: Good point! Probably yes. I will look into this.
Would it make this bug more severe?

Comment (njhale) [reply pkg/controller/registry/resolver/rbac.go:150]: I don't think it will affect the severity of the bug. Your current fix is still shrinking the number of possible collision cases, just not to zero. At a glance, I think we just need to add the CSV namespace to the `generateName` input somehow.

**Comment by matskiv** [comment]
The last commit:
- should address @njhale concern about collision on ClusterBinding, as well as some other possible collisions/edge cases.
- fully addresses #1625 - it will create distinct roles for each ServiceAccount, even if the rules are the same.
- brings back ServiceAccount name into (Cluster)Role name, as that was fairly convenient when troubleshooting

Looking forward to feedback. Cheers.

**Comment by matskiv** [comment]
Looks like `ci/prow/e2e-aws-olm` tests are failing for different reasons between the runs:

```
 [Fail] Install Plan with deprecated version CRD Test [It] upgrade CRD with deprecated version 
FAIL! -- 117 Passed | 1 Failed | 1 Pending | 3 Skipped 
```
``` 
[Fail] CSV [It] API service resource not migrated if not adoptable 
FAIL! -- 117 Passed | 1 Failed | 1 Pending | 3 Skipped 
```
```
 [Fail] Catalog [It] delete gRPC registry pod triggers recreation 
FAIL! -- 117 Passed | 1 Failed | 1 Pending | 3 Skipped 
```
