### PR TITLE
UT - add possible error message patterns for resolve failure

### LINKED ISSUE #2564: UT - resolver " FAIL: TestSolveOperators_WithSystemConstraints"
## Bug Report
Unit test - resolver_test.go  " FAIL: TestSolveOperators_WithSystemConstraints"
https://github.com/operator-framework/operator-lifecycle-manager/runs/4756877867?check_suite_focus=true#step:5:53

```
--- FAIL: TestSolveOperators_WithSystemConstraints (0.01s)
    resolver_test.go:164: 
        	Error Trace:	resolver_test.go:164
        	Error:      	"constraints not satisfiable: package: packageC is not white listed, package: packageB is not white listed, subscription packageA-alpha requires test-catalog/test-namespace/alpha/packageA.v1, subscription packageA-alpha exists, bundle packageA.v1 requires an operator providing an API with group: g, version: v, kind: k" does not contain "packageA is not white listed"
        	Test:       	TestSolveOperators_WithSystemConstraints
        	Messages:   	Test Runtime constraints don't allow A failed
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=warning msg="could not unambiguously infer package name for \"packageA.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [packageA.v1]"
time="2022-01-10T03:41:22Z" level=info msg="considered csvs without properties annotation during resolution: [opA.v1.0.0 opB.v1.0.0]"
time="2022-01-10T03:41:23Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
constraints not satisfiable: subscription a-alpha requires catsrc/catsrc-namespace/alpha/a.v1, subscription a-alpha exists, catsrc/catsrc-namespace/alpha/a.v1 and catsrc/catsrc-namespace/beta/a.v2 originate from package a, subscription a-beta requires catsrc/catsrc-namespace/beta/a.v2, subscription a-beta exists
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:24Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:24Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"b.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1 b.v1]"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"b.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1 b.v1]"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1 b.v1]"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
time="2022-01-10T03:41:25Z" level=warning msg="could not unambiguously infer package name for \"a.v1\" (found 0 distinct package names)"
time="2022-01-10T03:41:25Z" level=info msg="considered csvs without properties annotation during resolution: [a.v1]"
FAIL
FAIL	github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver	3.763s

```

**What did you do?**
CI Unit test intermittently fails at  TestSolveOperators_WithSystemConstraints.

**What did you expect to see?**
No failure

**What did you see instead? Under which circumstances?**
Failure above.

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**
The test fails when the error message doesn't have the expected string.  There are different error messages generated by the test and they are also valid error messages.   This change accept multiple strings as the expected string in the error messages.
Here are valid error messages that I captured so far:
```
subscription packageA-alpha requires test-catalog/test-namespace/alpha/packageA.v1, subscription packageA-alpha exists, package: packageC is not white listed, bundle packageA.v1 requires an operator providing an API with group: g, version: v, kind: k, package: packageB is not white listed
package: packageC is not white listed, package: packageB is not white listed, subscription packageA-alpha requires test-catalog/test-namespace/alpha/packageA.v1, subscription packageA-alpha exists, bundle packageA.v1 requires an operator providing an API with group: g, version: v, kind: k
subscription packageA-alpha requires test-catalog/test-namespace/alpha/packageA.v1, subscription packageA-alpha exists, package: packageA is not white listed
package: packageA is not white listed, subscription packageA-alpha requires test-catalog/test-namespace/alpha/packageA.v1, subscription packageA-alpha exists
```

**Motivation for the change:**
Closes #2564 
**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by akihikokuroda** [comment]
The Unit test failure should be addressed in https://github.com/operator-framework/operator-lifecycle-manager/pull/2547

File: pkg/controller/registry/resolver/resolver_test.go [hunk 1]
```diff
@@ -144,7 +145,7 @@ func TestSolveOperators_WithSystemConstraints(t *testing.T) {
 			expectedOperators:         nil,
 			csvs:                      nil,
 			subs:                      []*v1alpha1.Subscription{packageASub},
-			err:                       "packageA is not white listed",
+			err:                       []string{"packageA is not white listed", "packageB is not white listed"},
```
Comment (awgreene) [inline pkg/controller/registry/resolver/resolver_test.go:148]: I believe that it makes more sense to improve this test by whitelisting the other packages:

```go
systemConstraintsProvider: whiteListConstraintProvider(packageB, packageC, packageD),
```
If you disagree, at least update the title of the test to more accurately reflect the next test.

**Review by awgreene — CHANGES_REQUESTED** [review]
Great work @akihikokuroda , I have a suggestion.

File: pkg/controller/registry/resolver/resolver_test.go (hunk 1 above)
Comment (akihikokuroda) [reply pkg/controller/registry/resolver/resolver_test.go:148]: I agree.  It makes sense.  I'll put the suggested changes.

**Comment by awgreene** [comment]
@perdasilva and I spoke about this offline, and we think it might be best to leave #2564 open to track the non-deterministic behavior of OLM in this space. When OLM is deterministic, it should reintroduce a test that is similar to the existing format.

**Comment by timflannagan** [comment]
Holding so the bot doesn't go crazy.

/hold

**Comment by timflannagan** [comment]
Forcing merging as this PR doesn't affect anything that would influence e2e failures.
