### PR TITLE
put mutex around installplan creation

### LINKED ISSUE #2544: e2e Subscription    "with starting CSV" error
## Bug Report
e2e Subscription    "with starting CSV" error
https://github.com/operator-framework/operator-lifecycle-manager/runs/4628064669?check_suite_focus=true#step:4:3404

```
Subscription 
  with starting CSV
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:358

[BeforeEach] Subscription
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:57
created the subscription-e2e-mjc8n testing namespace
[It] with starting CSV
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:358
Creating catalog source mock-nginx-vf7pc in namespace subscription-e2e-mjc8n...
Catalog source mock-nginx-vf7pc created
waiting for catalog pod mock-nginx-vf7pc to be available (for sync) - NO_CONNECTION
waiting for catalog pod mock-nginx-vf7pc to be available (for sync) - CONNECTING
waiting for catalog pod mock-nginx-vf7pc to be available (for sync) - TRANSIENT_FAILURE
waiting for catalog pod mock-nginx-vf7pc to be available (for sync) - TRANSIENT_FAILURE
catalog mock-nginx-vf7pc pod with address mock-nginx-vf7pc.subscription-e2e-mjc8n.svc:50051
17:26:19.8094:  (): nil
waiting for sub-nginx-22dj9 to have installplan ref
17:26:20.8107:  (): nil
waiting for sub-nginx-22dj9 to have installplan ref
17:26:21.8102:  (): nil
waiting for sub-nginx-22dj9 to have installplan ref
17:26:22.8103: UpgradePending (nginx-a): &ObjectReference{Kind:InstallPlan,Namespace:subscription-e2e-mjc8n,Name:install-728hg,UID:5994cb0c-655d-465d-89b2-b4835a66bf1d,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:10338,FieldPath:,}
waiting for sub-nginx-22dj9 to have installplan ref
installplan install-728hg is in phase RequiresApproval
Deleting config map mock-nginx-vf7pc-configmap...
Deleting catalog source mock-nginx-vf7pc...
[AfterEach] Subscription
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:61
collecting the subscription-e2e-mjc8n namespace artifacts as the 'with starting CSV' test case failed
collecting logs in the ./artifacts/ artifacts directory
Storing the test artifact output in the artifacts/subscription-e2e-mjc8n directory
Collecting get catalogsources -o yaml output...
Collecting get subscriptions -o yaml output...
Collecting get operatorgroups -o yaml output...
Collecting get clusterserviceversions -o yaml output...
Collecting get installplans -o yaml output...
Collecting get pods -o wide output...
Collecting get events --sort-by .lastTimestamp output...
tearing down the subscription-e2e-mjc8n namespace


• Failure [58.732 seconds]
Subscription
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:52
  with starting CSV [It]
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:358

  
  	Error Trace:	subscription_e2e_test.go:439
  	            				runner.go:113
  	            				runner.go:64
  	            				it_node.go:26
  	            				spec.go:215
  	            				spec.go:138
  	            				spec_runner.go:200
  	            				spec_runner.go:170
  	            				spec_runner.go:66
  	            				suite.go:79
  	            				ginkgo_dsl.go:238
  	            				ginkgo_dsl.go:221
  	            				e2e_test.go:59
  	Error:      	"[{{InstallPlan operators.coreos.com/v1alpha1} {install-6l24h install- subscription-e2e-mjc8n  02bd3ccb-e1e8-498a-8ba5-a3729cd849dc 10347 %!s(int64=1) 2021-12-24 17:26:22 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [{operators.coreos.com/v1alpha1 Subscription sub-nginx-22dj9 e35588d9-8d0e-4222-a85a-1a6d5fd2e432 %!s(*bool=0xc001cec74a) %!s(*bool=0xc001cec749)}] []  [{catalog Update operators.coreos.com/v1alpha1 2021-12-24 17:26:22 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:ownerReferences":{".":{},"k:{\"uid\":\"e35588d9-8d0e-4222-a85a-1a6d5fd2e432\"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{".":{},"f:approval":{},"f:approved":{},"f:clusterServiceVersionNames":{},"f:generation":{}},"f:status":{".":{},"f:catalogSources":{},"f:phase":{},"f:plan":{}}} }]} {  [nginx-a] Manual %!s(bool=false) %!s(int=2)} {RequiresApproval [] [mock-nginx-vf7pc] [nginx-a: nginx-a[operators.coreos.com/v1alpha1/ClusterServiceVersion (mock-nginx-vf7pc/subscription-e2e-mjc8n)] (Unknown) nginx-a: insblh9j.cluster.com[apiextensions.k8s.io/v1/CustomResourceDefinition (mock-nginx-vf7pc/subscription-e2e-mjc8n)] (Unknown)] [] nil <nil> }} {{InstallPlan operators.coreos.com/v1alpha1} {install-728hg install- subscription-e2e-mjc8n  5994cb0c-655d-465d-89b2-b4835a66bf1d 10344 %!s(int64=1) 2021-12-24 17:26:21 +0000 UTC <nil> %!s(*int64=<nil>) map[operators.coreos.com/nginx-mjn2k.subscription-e2e-mjc8n:] map[] [{operators.coreos.com/v1alpha1 Subscription sub-nginx-22dj9 e35588d9-8d0e-4222-a85a-1a6d5fd2e432 %!s(*bool=0xc001ceca1a) %!s(*bool=0xc001ceca19)}] []  [{catalog Update operators.coreos.com/v1alpha1 2021-12-24 17:26:21 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:ownerReferences":{".":{},"k:{\"uid\":\"e35588d9-8d0e-4222-a85a-1a6d5fd2e432\"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{".":{},"f:approval":{},"f:approved":{},"f:clusterServiceVersionNames":{},"f:generation":{}},"f:status":{".":{},"f:catalogSources":{},"f:phase":{},"f:plan":{}}} } {olm Update operators.coreos.com/v1alpha1 2021-12-24 17:26:22 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:operators.coreos.com/nginx-mjn2k.subscription-e2e-mjc8n":{}}}} }]} {  [nginx-a] Manual %!s(bool=false) %!s(int=1)} {RequiresApproval [] [mock-nginx-vf7pc] [nginx-a: nginx-a[operators.coreos.com/v1alpha1/ClusterServiceVersion (mock-nginx-vf7pc/subscription-e2e-mjc8n)] (Unknown) nginx-a: insblh9j.cluster.com[apiextensions.k8s.io/v1/CustomResourceDefinition (mock-nginx-vf7pc/subscription-e2e-mjc8n)] (Unknown)] [] nil <nil> }}]" should have 1 item(s), but has 2
  	Test:       	Subscription with starting CSV
  
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1033

  Full Stack Trace
  github.com/stretchr/testify/require.Len(0x7fe2dc6b3aa0, 0xc00103ec40, 0x2f58a20, 0xc001abcdf8, 0x1, 0x0, 0x0, 0x0)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1033 +0xdb
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.8()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:439 +0x1208
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc000794780)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x2d6
  testing.tRunner(0xc000794780, 0x357d988)
  	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1193 +0xef
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1238 +0x2b3
```

**What did you do?**
CI e2e test failed in a pull request

**What did you expect to see?**
No error

**What did you see instead? Under which circumstances?**
Error above

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**
This PR makes the check if the InstallPlan has to be created and the creation of the installplan in a locked block so that 2 namespace queue workers don't create the Installplan for the subscription.

**Motivation for the change:**

Closes #2544 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by perdasilva — COMMENTED** [review]
lgtm - it could be worth while to add some comments to explain why the lock is needed, maybe even reference the issue. Might help other people keep an eye on these types of race conditions, etc.

**Comment by akihikokuroda** [comment]
The e2e test failure is addressed in https://github.com/operator-framework/operator-lifecycle-manager/issues/2542.

**Comment by perdasilva** [comment]
@akihikokuroda could you please rebase

File: pkg/controller/operators/catalog/operator.go [hunk 1]
```diff
@@ -1168,6 +1169,9 @@ func (o *Operator) ensureInstallPlan(logger *logrus.Entry, namespace string, gen
 		return nil, err
 	}
 
+	o.muInstallPlan.Lock()
+	defer o.muInstallPlan.Unlock()
```
Comment (timflannagan) [inline pkg/controller/operators/catalog/operator.go:1173]: @njhale Any idea on whether this might also solve the duplicate installplan resources getting generated when a subscription gets created? I can't seem to dig up the BZ anymore (maybe we closed that out as wontfix at some point?).

File: pkg/controller/operators/catalog/operator.go [hunk 2]
```diff
@@ -1167,6 +1168,9 @@ func (o *Operator) ensureInstallPlan(logger *logrus.Entry, namespace string, gen
...
```
Comment (timflannagan) [inline pkg/controller/operators/catalog/operator.go:1172]: Coming back to this after this has been siting for a while: can we add an explanation as to why this might be needed?

Comment (akihikokuroda) [reply pkg/controller/operators/catalog/operator.go:1172]: Yes, I think so.  I can add the explanation in a comment here.

**Comment by timflannagan** [comment]
@akihikokuroda Can you rebase this when you get a chance? I think this is ready to go.
