### PR TITLE
fix disable copied csv e2e test failure

### LINKED ISSUE #2542: e2e "should have copied CSVs in all other Namespaces" failure
## Bug Report

e2e "should have copied CSVs in all other Namespaces" failure in CI build
https://github.com/operator-framework/operator-lifecycle-manager/runs/4622357457?check_suite_focus=true#step:4:1621

```
Disabling copied CSVs when Copied CSVs are toggled back on 
  should have copied CSVs in all other Namespaces
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4366

[BeforeEach] when Copied CSVs are toggled back on
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4340
[It] should have copied CSVs in all other Namespaces
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4366


• Failure [60.011 seconds]
Disabling copied CSVs
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4177
  when Copied CSVs are toggled back on
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4339
    should have copied CSVs in all other Namespaces [It]
    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4366

    Timed out after 60.001s.
    Expected success, but got an error:
        <*errors.errorString | 0xc000b67ea0>: {
            s: "0 copied CSVs found, expected 6",
        }
        0 copied CSVs found, expected 6

    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4392

    Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func6.3.2()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4392 +0xc2
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc000377200)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x2d6
    testing.tRunner(0xc000377200, 0x357c3c8)
    	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
    	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1238 +0x2b3
```
**What did you do?**
CI build failure 
https://github.com/operator-framework/operator-lifecycle-manager/runs/4622357457?check_suite_focus=true#step:4:1621

**What did you expect to see?**
No error

**What did you see instead? Under which circumstances?**
Error above

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**
The all tests in ` Describe("Disabling copied CSVs"` need a namespace, operatorgroup and csv but they are setup only for the first test.  These are not cleaned up after the test so the following tests success when the tests are executed from top to bottom.  This PR adds the setup and clean up for all tests in "Disabling copied CSVs".

**Motivation for the change:**
Closes #2542 
**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by akihikokuroda** [comment]
The unit test failure is addressed in https://github.com/operator-framework/operator-lifecycle-manager/issues/2522

File: test/e2e/csv_e2e_test.go [hunk 1]
```diff
@@ -4204,29 +4204,68 @@ var _ = Describe("Disabling copied CSVs", func() {
...
+			if err := ctx.Ctx().Client().Create(context.TODO(), &csv); err != nil && !k8serrors.IsAlreadyExists(err) {
+				ctx.Ctx().Logf("Unable to create csv: %v", err)
+				return err
+			}
+
+			return nil
+		}).Should(Succeed())
+
+	})
+	AfterEach(func() {
```
Comment (perdasilva) [inline test/e2e/csv_e2e_test.go:4257]: suggestion: maybe we could wrap this in an `Eventually` as not to fail completely on transient network errors. Or does the client already have a retry policy?

Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go:4257]: Thanks for review!  I'll make the suggested changes.

File: test/e2e/csv_e2e_test.go [hunk 2]
```diff
@@ -4204,29 +4204,78 @@ var _ = Describe("Disabling copied CSVs", func() {
...
+		Eventually(func() error {
+			err := ctx.Ctx().Client().Delete(context.TODO(), &csv)
+			if err != nil {
```
Comment (perdasilva) [inline test/e2e/csv_e2e_test.go:4260]: question: are you sure you don't need to check for "NotFound" failures here as well?

Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go:4260]: You are right.  I'll add it.  Thanks!

File: test/e2e/csv_e2e_test.go [hunk 3]
```diff
@@ -4204,29 +4204,78 @@ var _ = Describe("Disabling copied CSVs", func() {
...
-				if err := ctx.Ctx().Client().Create(context.TODO(), &operatorGroup); err != nil && !k8serrors.IsAlreadyExists(err) {
-					ctx.Ctx().Logf("Unable to create og: %v", err)
-					return err
-				}
+			operatorGroup = operatorsv1.OperatorGroup{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:      genName("csv-toggle-test-"),
+					Namespace: ns.GetName(),
+				},
+			}
```
Comment (timflannagan) [inline test/e2e/csv_e2e_test.go:4221]: Can we use the [`SetupGeneratedTestNamespace`](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/test/e2e/util.go#L954) helper function instead, which is a way to generate a test namespace + an OperatorGroup resource? That allows us to also use the [`TeardownNamespace`](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/test/e2e/util.go#L982) helper function to also collect test artifacts when an individual test case fails.

For a concrete example of this pattern: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/test/e2e/subscription_e2e_test.go#L58.

Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go:4221]: Thanks!  I'll take a look.

Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go]: I had to tweak SetupGeneratedTestNamespace function a little bit for this test.

Comment (timflannagan) [reply test/e2e/csv_e2e_test.go]: Any reason you had to change around that helper function? It's not immediately clear to me when looking at these changes again, as the output of the previous and current implementation(s) all appear to have the same output:

- A namespace is created
- An OperatorGroup that targets the generated namespace is created

Am I missing something?

File: test/e2e/csv_e2e_test.go [hunk 4]
```diff
@@ -4175,58 +4175,61 @@ var _ = Describe("ClusterServiceVersion", func() {
...
+		ns corev1.Namespace
+		csv operatorsv1alpha1.ClusterServiceVersion
 
-	operatorGroup := operatorsv1.OperatorGroup{
-		ObjectMeta: metav1.ObjectMeta{
-			Name:      genName("csv-toggle-test-"),
-			Namespace: ns.GetName(),
-		},
-	}
+	)
```
Comment (timflannagan) [inline test/e2e/csv_e2e_test.go:4182]: nit: extra newline; the sanity check should identify this issue, but the test/e2e package is currently excluded from those linting checks. we'll eventually remove that exclusion, so I think I'd prefer to fix this here, vs. later.

File: test/e2e/csv_e2e_test.go [hunk 5]
```diff
@@ -4175,58 +4175,61 @@ var _ = Describe("ClusterServiceVersion", func() {
...
+			}
 
-				if err := ctx.Ctx().Client().Create(context.TODO(), &operatorGroup); err != nil && !k8serrors.IsAlreadyExists(err) {
-					ctx.Ctx().Logf("Unable to create og: %v", err)
-					return err
-				}
+			if err := ctx.Ctx().Client().Create(context.TODO(), &csv); err != nil && !k8serrors.IsAlreadyExists(err) {
+				ctx.Ctx().Logf("Unable to create csv: %v", err)
+				return err
+			}
```
Comment (timflannagan) [inline test/e2e/csv_e2e_test.go:4214]: Do we need to wrap this in an Eventually block as well?

File: test/e2e/csv_e2e_test.go [hunk 6]
```diff
@@ -4175,58 +4175,61 @@ var _ = Describe("ClusterServiceVersion", func() {
...
+			return nil
+		}).Should(Succeed())
 
-				return nil
-			}).Should(Succeed())
-		})
+	})
+	AfterEach(func() {
+		Eventually(func() error {
+			err := ctx.Ctx().Client().Delete(context.TODO(), &csv)
```
Comment (timflannagan) [inline test/e2e/csv_e2e_test.go:4222]: (this is applicable to all context.TODO references in this PRs' changes)

nit: can we use context.Background() here instead of context.TODO() to be consistent with the rest of the csv_e2e_test.go testing file?

File: test/e2e/csv_e2e_test.go (hunk 4 above)
Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go:4182]: Thanks!  I take it out.

File: test/e2e/csv_e2e_test.go (hunk 5 above)
Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go:4214]: It's in the  Eventually block now.  I'll take it out.

File: test/e2e/csv_e2e_test.go (hunk 6 above)
Comment (akihikokuroda) [reply test/e2e/csv_e2e_test.go]: I'll make changes.  Thanks!

**Comment by timflannagan** [comment]
@akihikokuroda It looks like you need to rebase against master to make branch protection rules happy.

**Comment by timflannagan** [comment]
@akihikokuroda Apologies - can you rebase this PR once more :laughing: - we should prioritize this merging before any other PRs at this point.
