### PR TITLE
wait for catalogsource status ready before creating subscription 

### LINKED ISSUE #2600: e2e - "should create a Subscription for the latest entry providing the required GVK" failure
## Bug Report

e2e - "should create a Subscription for the latest entry providing the required GVK" failed.
https://github.com/operator-framework/operator-lifecycle-manager/runs/4957261384?check_suite_focus=true#step:4:154

```
Subscription when an entry in the middle of a channel does not provide a required GVK 
  should create a Subscription for the latest entry providing the required GVK
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:106

[BeforeEach] Subscription
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:57
created the subscription-e2e-f9m6s testing namespace
[BeforeEach] when an entry in the middle of a channel does not provide a required GVK
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:70
Creating catalog source test-catalog in namespace subscription-e2e-f9m6s...
Catalog source test-catalog created
[It] should create a Subscription for the latest entry providing the required GVK
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:106
[AfterEach] when an entry in the middle of a channel does not provide a required GVK
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:102
Deleting config map test-catalog-configmap...
Deleting catalog source test-catalog...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
waiting for the catalog source test-catalog-8f667 pod to be deleted...
[AfterEach] Subscription
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:61
collecting the subscription-e2e-f9m6s namespace artifacts as the 'should create a Subscription for the latest entry providing the required GVK' test case failed
collecting logs in the ./artifacts/ artifacts directory
Storing the test artifact output in the artifacts/subscription-e2e-f9m6s directory
Collecting get catalogsources -o yaml output...
Collecting get subscriptions -o yaml output...
Collecting get operatorgroups -o yaml output...
Collecting get clusterserviceversions -o yaml output...
Collecting get installplans -o yaml output...
Collecting get pods -o wide output...
No resources found in subscription-e2e-f9m6s namespace.
Collecting get events --sort-by .lastTimestamp output...
tearing down the subscription-e2e-f9m6s namespace


• Failure [71.676 seconds]
Subscription
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:52
  when an entry in the middle of a channel does not provide a required GVK
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:65
    should create a Subscription for the latest entry providing the required GVK [It]
    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:106

    Timed out after 60.003s.
    Expected
        <[]v1alpha1.Subscription | len:1, cap:1>: [
            {
                TypeMeta: {
                    Kind: "Subscription",
                    APIVersion: "operators.coreos.com/v1alpha1",
                },
                ObjectMeta: {
                    Name: "test-subscription",
                    GenerateName: "",
                    Namespace: "subscription-e2e-f9m6s",
                    SelfLink: "",
                    UID: "943d1207-434a-4bc2-9651-813ec1d6d49b",
                    ResourceVersion: "1166",
                    Generation: 1,
                    CreationTimestamp: {
                        Time: 2022-01-26T20:26:50Z,
                    },
                    DeletionTimestamp: nil,
                    DeletionGracePeriodSeconds: nil,
                    Labels: {
                        "operators.coreos.com/root.subscription-e2e-f9m6s": "",
                    },
                    Annotations: nil,
                    OwnerReferences: nil,
                    Finalizers: nil,
                    ClusterName: "",
                    ManagedFields: [
                        {
                            Manager: "catalog",
                            Operation: "Update",
                            APIVersion: "operators.coreos.com/v1alpha1",
                            Time: {
                                Time: 2022-01-26T20:26:50Z,
                            },
                            FieldsType: "FieldsV1",
                            FieldsV1: {
                                Raw: "{\"f:status\":{\".\":{},\"f:catalogHealth\":{},\"f:conditions\":{},\"f:lastUpdated\":{}}}",
                            },
                            Subresource: "",
                        },
                        {
                            Manager: "e2e-local.test",
                            Operation: "Update",
                            APIVersion: "operators.coreos.com/v1alpha1",
                            Time: {
                                Time: 2022-01-26T20:26:50Z,
                            },
                            FieldsType: "FieldsV1",
                            FieldsV1: {
                                Raw: "{\"f:spec\":{\".\":{},\"f:channel\":{},\"f:installPlanApproval\":{},\"f:name\":{},\"f:source\":{},\"f:sourceNamespace\":{}}}",
                            },
                            Subresource: "",
                        },
                        {
                            Manager: "olm",
                            Operation: "Update",
                            APIVersion: "operators.coreos.com/v1alpha1",
                            Time: {
                                Time: 2022-01-26T20:26:51Z,
                            },
                            FieldsType: "FieldsV1",
                            FieldsV1: {
                                Raw: "{\"f:metadata\":{\"f:labels\":{\".\":{},\"f:operators.coreos.com/root.subscription-e2e-f9m6s\":{}}}}",
                            },
                            Subresource: "",
                        },
                    ],
                },
                Spec: {
                    CatalogSource: "test-catalog",
                    CatalogSourceNamespace: "subscription-e2e-f9m6s",
                    Package: "root",
                    Channel: "channel-root",
                    StartingCSV: "",
                    InstallPlanApproval: "Automatic",
                    Config: nil,
                },
                Status: {
                    CurrentCSV: "",
                    InstalledCSV: "",
                    Install: nil,
                    State: "",
                    Reason: "",
                    InstallPlanGeneration: 0,
                    InstallPlanRef: nil,
                    CatalogHealth: [
                        {
                            CatalogSourceRef: {
                                Kind: "CatalogSource",
                                Namespace: "operator-lifecycle-manager",
                                Name: "operatorhubio-catalog",
                                UID: "f9a493d1-b183-4ede-9027-7cd63902b03c",
                                APIVersion: "operators.coreos.com/v1alpha1",
                                ResourceVersion: "956",
                                FieldPath: "",
                            },
                            LastUpdated: {
        ...
    
    Gomega truncated this representation as it exceeds 'format.MaxLength'.
    Consider having the object provide a custom 'GomegaStringer' representation
    or adjust the parameters in Gomega's 'format' package.
    
    Learn more here: https://onsi.github.io/gomega/#adjusting-output
    
    to contain element matching
        <*matchers.WithTransformMatcher | 0xc0027e9340>: {
            Transform: <func(v1alpha1.Subscription) v1alpha1.SubscriptionSpec>0x2939ba0,
            Matcher: <*matchers.EqualMatcher | 0xc00285da40>{
                Expected: <v1alpha1.SubscriptionSpec>{
                    CatalogSource: "test-catalog",
                    CatalogSourceNamespace: "subscription-e2e-f9m6s",
                    Package: "dependency",
                    Channel: "channel-dependency",
                    StartingCSV: "csv-dependency-3",
                    InstallPlanApproval: "",
                    Config: nil,
                },
            },
            transformArgType: <*reflect.rtype | 0x2d46f60>{size: 0x1c0, ptrdata: 0x1c0, hash: 2418679958, tflag: 7, align: 8, fieldAlign: 8, kind: 25, equal: nil, gcdata: 85, str: 316800, ptrToThis: 5620032},
            transformedValue: <v1alpha1.SubscriptionSpec>{
                CatalogSource: "test-catalog",
                CatalogSourceNamespace: "subscription-e2e-f9m6s",
                Package: "root",
                Channel: "channel-root",
                StartingCSV: "",
                InstallPlanApproval: "",
                Config: nil,
            },
        }

    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:113

    Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func22.3.3()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:113 +0x175
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xf908f9)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x268
    testing.tRunner(0xc0001e1a00, 0x3004318)
    	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1259 +0x102
    created by testing.(*T).Run
    	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1306 +0x35a
```
**What did you do?**
Check CI e2e test failure

**What did you expect to see?**
No error

**What did you see instead? Under which circumstances?**
error above

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**
The test doesn't want the catalogsource gRPC connection ready status before it creates the subscription for the catalogsource.

**Motivation for the change:**
Closes #2600 
**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

File: test/e2e/subscription_e2e_test.go [hunk 1]
```diff
@@ -95,6 +95,8 @@ var _ = Describe("Subscription", func() {
 			}
 
 			_, teardown = createInternalCatalogSource(ctx.Ctx().KubeClient(), ctx.Ctx().OperatorClient(), "test-catalog", generatedNamespace.GetName(), packages, crds, csvs)
+			_, err := fetchCatalogSourceOnStatus(ctx.Ctx().OperatorClient(), "test-catalog", generatedNamespace.GetName(), catalogSourceRegistryPodSynced)
```
Comment (timflannagan) [inline test/e2e/subscription_e2e_test.go:98]: Nice catch - I was under the impression that we made a clean sweep of anywhere we instantiate a grpc-based CatalogSource, and then subsequently create a Subscription, but this one feels easy to catch given the setup isn't super readable. It would be nice to avoid having to hardcode the "test-catalog" in two places here, but I won't block the PR for this.

Comment (timflannagan) [reply test/e2e/subscription_e2e_test.go:98]: Actually I'm somewhat second guessing this the more I think about it. I haven't played around with this locally, but looking at that test case failure output, it's not immediately clear to me why we need to simply wait for the CatalogSource to be reporting a "ready" state. Were you able to reproduce this test case failure locally?

Comment (akihikokuroda) [reply test/e2e/subscription_e2e_test.go:98]: I didn't reproduce this error locally but I saw this in the catalog-operator log of the CI e2e failure.
```
2022-01-19T20:00:24.250526731Z stderr F time="2022-01-19T20:00:24Z" level=debug msg="syncing catsrc" id=Zfz5K source=test-catalog
2022-01-19T20:00:24.250530131Z stderr F time="2022-01-19T20:00:24Z" level=debug msg="checking catsrc configmap state" id=Zfz5K source=test-catalog
2022-01-19T20:00:24.251445279Z stderr F time="2022-01-19T20:00:24Z" level=debug msg="check registry server healthy: true" id=Zfz5K source=test-catalog
2022-01-19T20:00:24.25145768Z stderr F time="2022-01-19T20:00:24Z" level=debug msg="registry state good" id=Zfz5K source=test-catalog
2022-01-19T20:00:28.931802007Z stderr F time="2022-01-19T20:00:28Z" level=debug msg="Got source event: grpc.SourceState{Key:registry.CatalogKey{Name:\"test-catalog\", Namespace:\"subscription-e2e-gcqhv\"}, State:3}"
2022-01-19T20:00:28.931816007Z stderr F time="2022-01-19T20:00:28Z" level=info msg="state.Key.Namespace=subscription-e2e-gcqhv state.Key.Name=test-catalog state.State=TRANSIENT_FAILURE"
2022-01-19T20:00:28.931824208Z stderr F time="2022-01-19T20:00:28Z" level=debug msg="syncing catsrc" id=j7VvG source=test-catalog
2022-01-19T20:00:28.931827808Z stderr F time="2022-01-19T20:00:28Z" level=debug msg="checking catsrc configmap state" id=j7VvG source=test-catalog
2022-01-19T20:00:28.939247402Z stderr F time="2022-01-19T20:00:28Z" level=debug msg="check registry server healthy: true" id=j7VvG source=test-catalog
2022-01-19T20:00:28.939260203Z stderr F time="2022-01-19T20:00:28Z" level=debug msg="registry state good" id=j7VvG source=test-catalog
2022-01-19T20:00:28.956912641Z stderr F I0119 20:00:28.955396       1 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"", Name:"subscription-e2e-gcqhv", UID:"dfe83254-ba15-438f-badf-dd3b79c12036", APIVersion:"v1", ResourceVersion:"815", FieldPath:""}): type: 'Warning' reason: 'ResolutionFailed' [error using catalog test-catalog (in namespace subscription-e2e-gcqhv): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.185.140:50051: connect: connection refused", error using catalog operatorhubio-catalog (in namespace operator-lifecycle-manager): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.27.145:50051: connect: connection refused"]
2022-01-19T20:00:28.956949443Z stderr F I0119 20:00:28.956796       1 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"", Name:"subscription-e2e-gcqhv", UID:"dfe83254-ba15-438f-badf-dd3b79c12036", APIVersion:"v1", ResourceVersion:"815", FieldPath:""}): type: 'Warning' reason: 'ResolutionFailed' [error using catalog test-catalog (in namespace subscription-e2e-gcqhv): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.185.140:50051: connec\
t: connection refused", error using catalog operatorhubio-catalog (in namespace operator-lifecycle-manager): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.96.27.145:50051: connect: connec\
tion refused"]
```
This shows that the latest gRPC status is `TRANSIENT_FAILURE` but the status of the catalogsource is 
`check registry server healthy: true` and `registry state good`.
Then the subscription is created and issue the `list bundles` request and failed.

The catalogsource sync has checks if the pod of the registry is up, the resources for the registry (service, service accout, role, rolebinding, etc) are OK. 
 It also has the gRPC status separately.

Comment (timflannagan) [reply test/e2e/subscription_e2e_test.go:98]: Thanks - I think that explanation sounds reasonable to me. In any case, this change is harmless so we can always re-open this issue if we misdiagnosed the root cause.

/approve
/lgtm
