### PR TITLE
Bug 1899588: Only re-create operator resource if it has existing components

### LINKED ISSUE #1932: Unable to remove Operator following removal of subscription, csv, and  CRDs
## Bug Report
**What did you do?**
1. Installed the [keycloak-operator](https://github.com/keycloak/keycloak-operator)
2. Removed the subscription and CSV following [the instructions](https://olm.operatorframework.io/docs/tasks/uninstall-operator/)
3. Removed the CRDs for the operator
4. Removed the operator 

**What did you expect to see?**
Operator should be removed

**What did you see instead? Under which circumstances?**

Operator is immediately recreated:
```
robert.williams@Mac0259:~/work/pdns% kubectl get operators
NAME                    AGE
keycloak-operator.iam   12m
postgresql.pgo          28h
robert.williams@Mac0259:~/work/pdns% kubectl delete operator keycloak-operator.iam
operator.operators.coreos.com "keycloak-operator.iam" deleted
robert.williams@Mac0259:~/work/pdns% kubectl get operators
NAME                    AGE
keycloak-operator.iam   2s
postgresql.pgo          28h
```

The olm-operator pod logs the following:
```
2020-12-23T16:48:31.091Z        DEBUG   controllers.operator    reconciling operator    {"request": "/keycloak-operator.iam"}
2020-12-23T16:48:31.091Z        DEBUG   controllers.operator    Operator is already up-to-date  {"request": "/keycloak-operator.iam"}
2020-12-23T16:48:31.091Z        DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "operator", "request": "/keycloak-operator.iam"}
```

**Environment**
* operator-lifecycle-manager version:
v0.17.0

* Kubernetes version information:

```
robert.williams@Mac0259:~/work/pdns% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
EKS

**Additional context**
@benluddy offered a work-around of scaling the olm-operator deployment to 0, deleting and then scaling back up, which works.

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
This PR fixes a bug in the operator controller that causes it to
ALWAYS re-create deleted operator objects, even when no other resources
associated with that operator exist.

**Motivation for the change:**
Closes #1932

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage 
- [x] Sufficient end-to-end test coverage
- [ ] ~Docs updated or added to `/docs`~
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
/hold
Investigating a potential unit test improvement

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

File: pkg/controller/operators/operator_controller_test.go [hunk 1]
```diff
@@ -43,9 +44,54 @@ var _ = Describe("Operator Controller", func() {
...
+				)
+
+				for _, obj := range objs {
+					Expect(k8sClient.Create(ctx, obj.(client.Object))).To(Succeed())
+				}
+			})
+
+			AfterEach(func() {
+				for _, obj := range objs {
+					Expect(k8sClient.Get(ctx, testobj.NamespacedName(obj), obj.(client.Object))).To(Succeed())
```
Comment (njhale) [inline pkg/controller/operators/operator_controller_test.go:74]: Is this `Get` call necessary? Doesn't `Delete` return an error if the resource doesn't exist?

**Review by njhale — COMMENTED** [review]
Looking great!

I think the last thing we need to see before approval is an e2e test.

File: pkg/controller/operators/operator_controller_test.go (hunk 1 above)
Comment (joelanford) [reply pkg/controller/operators/operator_controller_test.go:74]: It shouldn't be necessary to do the `Get`, I don't think. This was a copy paste from existing test code. I'll remove and see if tests still pass.

File: test/e2e/operator_test.go [hunk 2]
```diff
@@ -196,6 +215,25 @@ var _ = Describe("Operator", func() {
 		// Ensure the reference to ns-a is eventually removed from o's status.components.refs field
 		By("removing a component's reference when it no longer exists")
 		componentRefEventuallyExists(w, false, getReference(scheme, nsA))
+
+		// Delete o
```
Comment (awgreene) [inline test/e2e/operator_test.go:219]: Should this step be required? If an operator has no resources should OLM clean it up?

File: pkg/controller/operators/operator_controller.go [hunk 3]
```diff
@@ -119,6 +120,12 @@ func (r *OperatorReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 	in := &operatorsv1.Operator{}
 	if err := r.Get(ctx, req.NamespacedName, in); err != nil {
 		if apierrors.IsNotFound(err) {
+			// If the Operator instance is not found, we're likely reconciling because
```
Comment (awgreene) [inline pkg/controller/operators/operator_controller.go:123]: Nit: OLM could use a delete predicate here to filter delete events, but that's probably overkill. Non-blocking

File: pkg/controller/operators/operator_controller_test.go [hunk 4]
```diff
@@ -92,7 +140,6 @@ var _ = Describe("Operator Controller", func() {
 
 			AfterEach(func() {
 				for _, obj := range objs {
-					Expect(k8sClient.Get(ctx, testobj.NamespacedName(obj), obj.(client.Object))).To(Succeed())
```
Comment (awgreene) [inline pkg/controller/operators/operator_controller_test.go:95]: Was this removed because the delete call would fail anyways?

**Review by awgreene — COMMENTED** [review]
Looks great - one or two questions but mostly for my own betterment.

File: test/e2e/operator_test.go (hunk 2 above)
Comment (njhale) [reply test/e2e/operator_test.go:219]: This is more of a comment on the design than of the PR.

I do think it makes sense to keep Operator resources around in the event users have cause to manually create/update them; e.g. a spec field that controls something.

File: pkg/controller/operators/operator_controller.go (hunk 3 above)
Comment (joelanford) [reply pkg/controller/operators/operator_controller.go:123]: There _are_ cases where we want to see the delete events. If an `Operator` resource is deleted, but some of the components associated with that operator still exist, we should re-create the deleted `Operator` resource (IIUC).

File: pkg/controller/operators/operator_controller_test.go (hunk 4 above)
Comment (joelanford) [reply pkg/controller/operators/operator_controller_test.go:95]: As I understood this, this was removed because it's unnecessary to `Get` the object before deleting it. It seems like the goal of this `AfterEach` block is to ensure the objects are deleted.
