### PR TITLE
test/e2e: Fix 'resource name may not be empty' failure in catalog templating test case

### LINKED ISSUE #2376: Flake: adding catalog template adjust image used
Occasionally, the `It adding catalog template adjusts image used` flakes where the resource name is empty. After a quick inspection, it looks like https://github.com/operator-framework/operator-lifecycle-manager/blob/master/test/e2e/catalog_e2e_test.go#L1079 could be the culprit where the `sourceName` is somehow empty. One possible solution is to update the `sourceName` to `source.GetName()`.

This is somewhat reproducible locally, but seems isolated to non-parallel e2e runs (e.g. NODES=1):

```
Catalog represents a store of bundles which OLM can use to install Operators
[90m/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:35[0m
  [91m[1madding catalog template adjusts image used [It][0m
  [90m/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:1036[0m

  [91mTimed out after 60.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc0007a2460>: {
          s: "resource name may not be empty",
      }
      resource name may not be empty[0m

  /go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:1075
```

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**
Update the 'adding catalog template adjusts image used' test case and
fix the issue where get requests for the test catalogsource were failing
due to the source.GetName() and source.GetNamespace() being empty, and
therefore the test catalogsource could never be updated.

Updating the test logic to avoid overwriting the `source` variable
during every poll by suppressing the variable returned appeared to be
the culprit. This was consistently reproducible on a cluster when
focusing on this single test and running the e2e suite directly.
After making these changes, I wasn't able to reproduce locally anymore.

**Motivation for the change:**
Reducing e2e flakes overtime.

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage
- [x] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/doc`
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
I'd recommend reviewing by the commits vs. the full diff as I sneaked in another commit to replace context.TODO -> context.Background commit too.

**Comment by timflannagan** [comment]
More context here as well: https://github.com/operator-framework/operator-lifecycle-manager/pull/2397#discussion_r751645888

File: test/e2e/catalog_e2e_test.go [hunk 1]
```diff
@@ -1099,7 +1105,7 @@ var _ = Describe("Catalog represents a store of bundles which OLM can use to ins
 			}
 
 			return false, nil
-		}, 5*time.Minute, 1*time.Second).Should(BeTrue())
+		}).Should(BeTrue())
 
 		// source should be the latest we got from the eventually block
 		Expect(source.Status.Conditions).ToNot(BeNil())
```
Comment (njhale) [inline test/e2e/catalog_e2e_test.go:1111]: nit: I suspect we could refactor most of the rest of this test into a matcher for the previous `Eventually` statement.

File: test/e2e/catalog_e2e_test.go [hunk 2]
```diff
@@ -1069,26 +1068,33 @@ var _ = Describe("Catalog represents a store of bundles which OLM can use to ins
...
 		Eventually(func() error {
-			source, err = crc.OperatorsV1alpha1().CatalogSources(source.GetNamespace()).Update(context.TODO(), source, metav1.UpdateOptions{})
+			source, err = crc.OperatorsV1alpha1().CatalogSources(source.GetNamespace()).Get(context.Background(), source.GetName(), metav1.GetOptions{})
+			if err != nil {
+				return err
+			}
+			// create an annotation using the kube templates
+			source.SetAnnotations(map[string]string{
+				catalogsource.CatalogImageTemplateAnnotation: fmt.Sprintf("quay.io/olmtest/catsrc-update-test:%s.%s.%s", catalogsource.TemplKubeMajorV, catalogsource.TemplKubeMinorV, catalogsource.TemplKubePatchV),
+			})
```
Comment (njhale) [inline test/e2e/catalog_e2e_test.go:1088]: nit: we _could_ define the map literal outside of this closure and set it here too

**Review by njhale — APPROVED** [review]
/approve
