### PR TITLE
fix e2e CSV metric is preserved failure

### LINKED ISSUE #2529: e2e CSV metric is preserved failed intermittently
## Bug Report

e2e CSV metric is preserved failed intermittently
https://github.com/operator-framework/operator-lifecycle-manager/runs/4548853424?check_suite_focus=true#step:4:11624
```
Metrics are generated for OLM managed resources Given an OperatorGroup that supports all namespaces when a CSV is created when the OLM pod restarts
  CSV metric is preserved
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:151

[BeforeEach] Metrics are generated for OLM managed resources
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:39
[BeforeEach] Given an OperatorGroup that supports all namespaces
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:46
STEP: using the default OperatorGroup created in BeforeSuite
[BeforeEach] when a CSV is created
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:126
 ():
Installing (InstallSucceeded): waiting for install components to report healthy
Succeeded (InstallSucceeded): install strategy completed with no errors
[BeforeEach] when the OLM pod restarts
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:148
[It] CSV metric is preserved
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:151
querying pod operator-lifecycle-manager/olm-operator-64cbf5d7c6-n5b6b
Retrieving metrics using scheme http
[AfterEach] when a CSV is created
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:137


• Failure [4.200 seconds]
Metrics are generated for OLM managed resources
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:32
  Given an OperatorGroup that supports all namespaces
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:45
    when a CSV is created
    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:121
      when the OLM pod restarts
      /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:147
	CSV metric is preserved [It]
	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:151

	Expected
            <[]e2e.Metric | len:2, cap:2>: [
                {Family: "csv_count", Labels: nil, Value: 0},
                {
                    Family: "csv_upgrade_count",
                    Labels: nil,
                    Value: 0,
                },
            ]
        to contain element matching
            <*e2e.LikeMetricMatcher | 0xc001a752d8>: {
                Predicates: [
                    {
                        f: 0x2c17960,
                        name: "WithFamily(csv_succeeded)",
                    },
                    {
                        f: 0x2c179e0,
                        name: "WithLabel(name=csv-test-9lf92-stable)",
                    },
                    {f: 0x2c17c20, name: "WithValue(1)"},
                ],
            }

        /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:152

        Full Stack Trace
        github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func12.2.3.4.2()
                /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go:152 +0x311
        github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc000653080)
                /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x2d6
        testing.tRunner(0xc000653080, 0x3470840)
                /opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1193 +0xef
        created by testing.(*T).Run
                /opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1238 +0x2b3
```

**What did you do?**
This error can be reproduced more often locally by adding a short delay in cmd/olm/main.go
```
diff --git a/cmd/olm/main.go b/cmd/olm/main.go
index efb1e00e0..08892a165 100644
--- a/cmd/olm/main.go
+++ b/cmd/olm/main.go
@@ -170,7 +170,7 @@ func main() {

        op.Run(ctx)
        <-op.Ready()
-
+time.Sleep(5*time.Second)
        // Emit CSV metric
        if err = op.EnsureCSVMetric(); err != nil {
		logger.WithError(err).Fatal("error emitting metrics for existing CSV")
```

**What did you expect to see?**
No error

**What did you see instead? Under which circumstances?**
Error above

**Environment**
* operator-lifecycle-manager version: master branch

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**

Adding wait for the metric are reemitted in the new pod in the e2e test.

**Motivation for the change:**
Close #2529 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

File: test/e2e/metrics_e2e_test.go [hunk 1]
```diff
@@ -149,9 +149,13 @@ var _ = Describe("Metrics are generated for OLM managed resources", func() {
 					restartDeploymentWithLabel(c, "app=olm-operator")
 				})
 				It("CSV metric is preserved", func() {
-					Expect(getMetricsFromPod(c, getPodWithLabel(c, "app=olm-operator"))).To(
-						ContainElement(LikeMetric(WithFamily("csv_succeeded"), WithName(csv.Name), WithValue(1))),
-					)
+					Eventually(func() []Metric {
+						return getMetricsFromPod(c, getPodWithLabel(c, "app=olm-operator"))
+					}).Should(ContainElement(LikeMetric(
```
Comment (timflannagan) [inline test/e2e/metrics_e2e_test.go:154]: I _think_ this is the right approach when I was looking into this issue. It wasn't clear to me whether we simply were attempting to get the pod metrics before the metrics port was even established, or the startup metric functionality had simply regressed. I'm inclined to think it's the latter, and in certain cluster environments, I could definitely see this test permafailing due to slower container/application start up times.

**Comment by timflannagan** [comment]
I'm going to give the e2e-tests action a couple of spins in any case to weed out any instability in any case - but these types of changes are super appreciated while we work towards reducing the overall CI noise in our current e2e suite. We should have a couple of changes inflight that will make the experience better (both in CI and local environments).

File: test/e2e/metrics_e2e_test.go [hunk 2]
```diff
@@ -567,6 +571,7 @@ func getMetricsFromPod(client operatorclient.ClientInterface, pod *corev1.Pod) [
 				m.Value = c.GetValue()
 			}
 			metrics = append(metrics, m)
+			fmt.Printf("metrics %+v\n", m)
```
Comment (timflannagan) [inline test/e2e/metrics_e2e_test.go:574]: It's unclear to me how much value we get logging the metrics. Did this help debug this test flake, or did you think it was improvement in e2e visibility? If so, can we use the `ctx.Ctx().Logf(...)` logger instead of fmt.Printf here, else we can just drop this log call entirely.

Comment (awgreene) [reply test/e2e/metrics_e2e_test.go:574]: Echoing this sentiment. I wouldn't mind if these metrics were printed on failure but otherwise these logs seem to offer little value add.

File: test/e2e/metrics_e2e_test.go (hunk 1 above)
Comment (awgreene) [reply test/e2e/metrics_e2e_test.go:154]: Retrying here is absolutely the correct approach. I suspect this test ran smoothly on the developers machine and does not transfer well to slow ci enviornments as @timflannagan suggested.

**Review by awgreene — CHANGES_REQUESTED** [review]
Great work @akihikokuroda, mostly just echoed what @timflannagan said.

File: test/e2e/metrics_e2e_test.go (hunk 1 above)
Comment (akihikokuroda) [reply test/e2e/metrics_e2e_test.go:154]: Thanks for review.!!

File: test/e2e/metrics_e2e_test.go (hunk 2 above)
Comment (akihikokuroda) [reply test/e2e/metrics_e2e_test.go:574]: Sorry, it was for my own debug.  I'll take it out.  Thanks!

**Comment by timflannagan** [comment]
Thanks for tackling this again - this is definitely one of the flakes that pops up frequently.

/lgtm

**Comment by awgreene** [comment]
/approve
Thanks again for the contribution towards OLM @akihikokuroda, these PRs are very impactful to the health of the project!
