### PR TITLE
fix e2e config map update triggers registry pod rollout failure

### LINKED ISSUE #2531: e2e config map update triggers registry pod rollout failure
## Bug Report
e2e config map update triggers registry pod rollout fails intermittently
https://github.com/operator-framework/operator-lifecycle-manager/runs/4548853424?check_suite_focus=true#step:4:11627

```
Catalog represents a store of bundles which OLM can use to install Operators
  config map update triggers registry pod rollout
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:202

[BeforeEach] Catalog represents a store of bundles which OLM can use to install Operators
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:39
[It] config map update triggers registry pod rollout
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:202
Creating catalog source mock-ocs-main-xdd2v in namespace operators...
Catalog source mock-ocs-main-xdd2v created
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - CONNECTING
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - TRANSIENT_FAILURE
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - TRANSIENT_FAILURE
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - CONNECTING
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - CONNECTING
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - TRANSIENT_FAILURE
waiting for catalog pod mock-ocs-main-xdd2v to be available (for sync) - TRANSIENT_FAILURE
catalog mock-ocs-main-xdd2v pod with address mock-ocs-main-xdd2v.operators.svc:50051
catalog mock-ocs-main-xdd2v pod with address mock-ocs-main-xdd2v.operators.svc:50051
waiting for catalog pod mock-ocs-main-xdd2v to be available (after catalog update) - TRANSIENT_FAILURE
waiting for catalog pod mock-ocs-main-xdd2v to be available (after catalog update) - TRANSIENT_FAILURE
catalog updated
catalog updated
Waiting for pods matching selector olm.catalogSource=mock-ocs-main-xdd2v,olm.configMapResourceVersion=10765 to match given conditions
Waiting for pods matching selector olm.catalogSource=mock-ocs-main-xdd2v,olm.configMapResourceVersion=10765 to match given conditions
Waiting for pods matching selector olm.catalogSource=mock-ocs-main-xdd2v,olm.configMapResourceVersion=10765 to match given conditions
[AfterEach] Catalog represents a store of bundles which OLM can use to install Operators
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:45
cleaning up ephemeral test resources...
deleting test subscriptions...
deleting test installplans...
deleting test catalogsources...
deleting test crds...
deleting test csvs...
test resources deleted


• Failure [366.184 seconds]
Catalog represents a store of bundles which OLM can use to install Operators
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:34
  config map update triggers registry pod rollout [It]
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:202
	Error Trace:    util_test.go:99
                                                catalog_e2e_test.go:282
                                                runner.go:113
                                                runner.go:64
                                                it_node.go:26
                                                spec.go:215
                                                spec.go:138
                                                spec_runner.go:200
                                                spec_runner.go:170
                                                spec_runner.go:66
                                                suite.go:79
                                                ginkgo_dsl.go:238
                                                ginkgo_dsl.go:221
                                                e2e_test.go:59
        Error:          Received unexpected error:
                        timed out waiting for the condition
        Test:           Catalog represents a store of bundles which OLM can use to install Operators config map update triggers registry pod rollout


  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1231

  Full Stack Trace
  github.com/stretchr/testify/require.NoError(0x7fec0c7322e8, 0xc001e88a40, 0x36e82e0, 0xc00020e730, 0x0, 0x0, 0x0)
        /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:1231 +0xcb
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.awaitPods(0x37692e8, 0xc001e88a40, 0x3778c40, 0xc000ee60f0, 0x7ffce6e96e8e, 0x9, 0xc000cfdbd0, 0x48, 0xc001bd3e30, 0x0, ...)
        /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/util_test.go:99 +0x1c5
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func2.5()
        /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:282 +0x19b8
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc00061ed80)
        /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x2d6
  testing.tRunner(0xc00061ed80, 0x3470840)
        /opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1193 +0xef
  created by testing.(*T).Run
        /opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1238 +0x2b3
```

**What did you do?**
I believe that the owner id injection into the configmap happened after the updated configmap is captured in the test is causing the revision mismatch between the pod and the configmap. 
```
2021-12-17T18:13:27.707746625Z stderr F time="2021-12-17T18:13:27Z" level=debug msg="syncing catsrc" id=jZYtf source=mock-ocs-main-m49pj
2021-12-17T18:13:27.707997525Z stderr F time="2021-12-17T18:13:27Z" level=debug msg="checking catsrc configmap state" id=jZYtf source=mock-ocs-main-m49pj
2021-12-17T18:13:27.715134526Z stderr F time="2021-12-17T18:13:27Z" level=debug msg="adopted configmap" id=jZYtf source=mock-ocs-main-m49pj
2021-12-17T18:13:27.716949326Z stderr F time="2021-12-17T18:13:27Z" level=debug msg="updating catsrc configmap state" id=jZYtf source=mock-ocs-main-m49pj
```

**What did you expect to see?**
No error
**What did you see instead? Under which circumstances?**
Error above

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

This change make sure the updated configmap is captured after the owner id is injected.  So the the revision id injected into the pod matches the revision id of the configmap

Closes #2531
**Description of the change:**
It doesn't seem a very good way but I can reproduce this failure by making this change.
```
--- a/pkg/controller/operators/catalog/operator.go
+++ b/pkg/controller/operators/catalog/operator.go
@@ -648,7 +648,7 @@ func (o *Operator) syncConfigMap(logger *logrus.Entry, in *v1alpha1.CatalogSourc
                return
        }
 
-       if wasOwned := ownerutil.EnsureOwner(configMap, in); !wasOwned || updateLabel {
+       if wasOwned := ownerutil.EnsureOwner(configMap, in); (in.Status.ConfigMapResource != nil && !in.Status.ConfigMapResource.IsAMatch(&configMap.ObjectMeta)) && (!wasOwned || updateLabel) {
                configMap, err = o.opClient.KubernetesInterface().CoreV1().ConfigMaps(configMap.GetNamespace()).Update(context.TODO(), configMap, metav1.UpdateOptions{})
                if err != nil {
                        syncError = fmt.Errorf("unable to write owner onto catalog source configmap - %v", err)
```

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

File: test/e2e/catalog_e2e_test.go [hunk 1]
```diff
@@ -272,6 +269,15 @@ var _ = Describe("Catalog represents a store of bundles which OLM can use to ins
 		})
 		Expect(err).ShouldNot(HaveOccurred())
 
+		Eventually(func() types.UID {
+			// Get updated configmap
+			updatedConfigMap, err := c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
+			Expect(err).ShouldNot(HaveOccurred())
+			return updatedConfigMap.ObjectMeta.OwnerReferences[0].UID
+		}).Should(Equal(fetchedUpdatedCatalog.ObjectMeta.UID))
+		updatedConfigMap, err := c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
```
Comment (awgreene) [inline test/e2e/catalog_e2e_test.go:278]: Nit, non-blocking: Can we add a space here so it is easier to read?

```suggestion
		}).Should(Equal(fetchedUpdatedCatalog.ObjectMeta.UID))
		
		updatedConfigMap, err := c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
```

Comment (awgreene) [inline test/e2e/catalog_e2e_test.go:278]: Alternatively, we could defined the updatedConfigMap upfront and avoid an additional `get` call:
```suggestion
                var updatedConfigMap corev1.ConfigMap
		Eventually(func() types.UID {
		       var err error
			// Get updated configmap
			updatedConfigMap, err = c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
			Expect(err).ShouldNot(HaveOccurred())
			return updatedConfigMap.ObjectMeta.OwnerReferences[0].UID
		}).Should(Equal(fetchedUpdatedCatalog.ObjectMeta.UID))
```

**Review by awgreene — CHANGES_REQUESTED** [review]
Thanks for improving our e2e test suite @akihikokuroda! I'm not particularly familiar with this test, but based on the issue reported in #2531, this fix seems appropriate. I had one small nit on implementation.

File: test/e2e/catalog_e2e_test.go (hunk 1 above)
Comment (akihikokuroda) [reply test/e2e/catalog_e2e_test.go:278]: Thanks for review.  I add the space.

Comment (akihikokuroda) [reply test/e2e/catalog_e2e_test.go:278]: Thanks!  It's better.  I'll take your suggested changes.

File: test/e2e/catalog_e2e_test.go [hunk 2]
```diff
@@ -272,6 +269,15 @@ var _ = Describe("Catalog represents a store of bundles which OLM can use to ins
 		})
 		Expect(err).ShouldNot(HaveOccurred())
 
+		var updatedConfigMap *corev1.ConfigMap
+		Eventually(func() types.UID {
+			var err error
+			// Get updated configmap
+			updatedConfigMap, err = c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
+			Expect(err).ShouldNot(HaveOccurred())
```
Comment (timflannagan) [inline test/e2e/catalog_e2e_test.go:277]: I have a couple of comments/questions:

- Do we need to add a length check to the `ObjectMeta.OwnerReferences` to ensure there's at least a single owner reference to avoid a panic down the line? It's unknown to me whether this is overkill, and whether we can rely on the owner references always being present. I'm mainly interested in guarding against panics being produced and us not catching them and/or making them harder to debug in the future.
- nit: Can we handle the error explicitly vs. using the gomega assertions, e.g.

```go
updatedConfigMap, err := ...
if err != nil {
    return err
}
...
```

/lgtm

Comment (akihikokuroda) [reply test/e2e/catalog_e2e_test.go:277]: Thanks!  I'll make both changes.

File: test/e2e/catalog_e2e_test.go [hunk 3]
```diff
@@ -272,6 +269,20 @@ var _ = Describe("Catalog represents a store of bundles which OLM can use to ins
...
+			// Get updated configmap
+			updatedConfigMap, err = c.KubernetesInterface().CoreV1().ConfigMaps(testNamespace).Get(context.Background(), fetchedInitialCatalog.Spec.ConfigMap, metav1.GetOptions{})
+			if err != nil {
+				return "", err
+			}
+			if len(updatedConfigMap.ObjectMeta.OwnerReferences) == 0 {
+				return "", nil
+			}
+			return updatedConfigMap.ObjectMeta.OwnerReferences[0].UID, nil
+		}).Should(Equal(fetchedUpdatedCatalog.ObjectMeta.UID))
```
Comment (timflannagan) [inline test/e2e/catalog_e2e_test.go:284]: What happens when an error is returned here? It looks like we only account for the UID comparison if I'm reading this correctly. Should we just return an empty string when an error is encountered, or just extend the Eventually to also check whether the error is nil?

Comment (timflannagan) [reply test/e2e/catalog_e2e_test.go:284]: Actually I don't think I'm super concerned with the error path here anymore, and I'm seeing this flake pop up more frequently recently, so I'm down to just push this through.

/lgtm

**Review by awgreene — APPROVED** [review]
Great work @akihikokuroda, approved.

**Comment by timflannagan** [comment]
@akihikokuroda Unfortunately, it looks like you'll need to rebase this to make branch protection happy :disappointed:
