### PR TITLE
InstallPlan wait for condition update

### LINKED ISSUE #2509: e2e failure Install Plan when an InstallPlan is created with no valid OperatorGroup present
## Bug Report

```
Install Plan when an InstallPlan is created with no valid OperatorGroup present 
  should clear clear up the condition in the InstallPlan status that contains an error message when a valid OperatorGroup is created
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3193

[BeforeEach] when an InstallPlan is created with no valid OperatorGroup present
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3167
[It] should clear clear up the condition in the InstallPlan status that contains an error message when a valid OperatorGroup is created
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3193
installplan ip is in phase Installing
[AfterEach] when an InstallPlan is created with no valid OperatorGroup present
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3245
[AfterEach] Install Plan
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:55
cleaning up ephemeral test resources...
deleting test subscriptions...
deleting test installplans...
deleting test catalogsources...
deleting test crds...
deleting test csvs...
test resources deleted


• Failure [1.148 seconds]
Install Plan
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:54
  when an InstallPlan is created with no valid OperatorGroup present
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3159
    should clear clear up the condition in the InstallPlan status that contains an error message when a valid OperatorGroup is created [It]
    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3193

    Expected
        <bool>: false
    to be true

    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3202

    Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func11.16.2()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:3202 +0x4f7
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xc000677080)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x296
    testing.tRunner(0xc000677080, 0x343f750)
    	/opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
    	/opt/hostedtoolcache/go/1.16.10/x64/src/testing/testing.go:1238 +0x2b3
```

**What did you do?**
I saw the failure here https://github.com/operator-framework/operator-lifecycle-manager/runs/4401450368?check_suite_focus=true

**What did you expect to see?**
Should not fail

**What did you see instead? Under which circumstances?**
Failure above

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by akihikokuroda**
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>

**Description of the change:**
There are a small gap between the phase update and the condition update of the InstallPlan.  This change makes sure the correct condition is put into the installplan at the beginning of the test.

**Motivation for the change:**
Closes #2509

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

File: test/e2e/installplan_e2e_test.go [hunk 1]
```diff
@@ -3192,14 +3192,24 @@ var _ = Describe("Install Plan", func() {
...
+					Expect(fetchedInstallPlan.Status.Phase).To(Equal(operatorsv1alpha1.InstallPlanPhaseInstalling))
+					if hasCondition(fetchedInstallPlan, cond) {
+						return true, nil
+					} else {
+						return false, nil
+					}
+				},
+				1*time.Minute,
+				interval,
+			).Should(BeTrue())
```
Comment (timflannagan) [inline test/e2e/installplan_e2e_test.go:3212]: WDYT about this implementation? I'm not entirely sure whether we care about returning an error here either, and can just return a bool instead?

```suggestion
			Eventually(func() (bool, error) {
				fetchedInstallPlan, err := fetchInstallPlanWithNamespace(GinkgoT(), crc, installPlanName, ns.GetName(), buildInstallPlanPhaseCheckFunc(operatorsv1alpha1.InstallPlanPhaseInstalling))
				if err != nil {
					return false, err
				}
				if fetchedInstallPlan.Status.Phase != operatorsv1alpha1.InstallPlanPhaseInstalling {
					return false, nil
				}
				return hasCondition(fetchedInstallPlan, cond), nil
			}, 1*time.Minute, interval).Should(BeTrue())
```

**Review by timflannagan — COMMENTED** [review]
Thanks for continuing to dish these flake/cleanup PRs out - I think these changes are reasonable. I just had one quick comment about simplifying the Eventually block. Any idea on how we could reproduce this more frequently to gauge whether these fixes will remove this flake?

**Comment by timflannagan** [comment]
@akihikokuroda I'm going to recycle the checks for this PR as well as we may have regressed in CI health in the past couple of weeks and I want to double check whether these changes pop up as failures in the e2e-tests workflow.

File: test/e2e/installplan_e2e_test.go (hunk 1 above)
Comment (akihikokuroda) [reply test/e2e/installplan_e2e_test.go:3212]: It looks better to me. I take your suggested changes and also take out the error return.  Thanks!

**Comment by akihikokuroda** [comment]
The unit test failure should be fixed by this: https://github.com/operator-framework/operator-lifecycle-manager/pull/2521

File: test/e2e/installplan_e2e_test.go [hunk 2]
```diff
@@ -3192,14 +3192,20 @@ var _ = Describe("Install Plan", func() {
...
+			Eventually(func() bool {
+				fetchedInstallPlan, err := fetchInstallPlanWithNamespace(GinkgoT(), crc, installPlanName, ns.GetName(), buildInstallPlanPhaseCheckFunc(operatorsv1alpha1.InstallPlanPhaseInstalling))
+				if err != nil {
+					return false
+				}
+				if fetchedInstallPlan.Status.Phase != operatorsv1alpha1.InstallPlanPhaseInstalling {
+					return false
+				}
+				return hasCondition(fetchedInstallPlan, cond)
+			}, 1*time.Minute, interval).Should(BeTrue())
```
Comment (awgreene) [inline test/e2e/installplan_e2e_test.go:3208]: Non-blocking nit: the minute timeout seems a bit arbitrary.

File: test/e2e/installplan_e2e_test.go [hunk 3]
```diff
@@ -3192,14 +3192,20 @@ var _ = Describe("Install Plan", func() {
 
 		It("should clear clear up the condition in the InstallPlan status that contains an error message when a valid OperatorGroup is created", func() {
 
-			// first check that a condition with a message exists
-			fetchedInstallPlan, err := fetchInstallPlanWithNamespace(GinkgoT(), crc, installPlanName, ns.GetName(), buildInstallPlanPhaseCheckFunc(operatorsv1alpha1.InstallPlanPhaseInstalling))
-			Expect(err).NotTo(HaveOccurred())
-			Expect(fetchedInstallPlan).NotTo(BeNil())
```
Comment (awgreene) [inline test/e2e/installplan_e2e_test.go:3198]: Based on [this](https://github.com/operator-framework/operator-lifecycle-manager/blob/dd804774acab78de3d7165d9461789e3c66920ba/test/e2e/installplan_e2e_test.go#L4099) return statement within the `fetchInstallPlanWithNamespace` function, it is possible that the `fetchedInstallPlan` will be nil if the `Get` call from the client ever returns `nil, nil`.

I can't think of a time where this could happen, but we should probably safeguard against it.

**Review by awgreene — CHANGES_REQUESTED** [review]
Two nits. Thanks for fixing this.

File: test/e2e/installplan_e2e_test.go (hunk 3 above)
Comment (akihikokuroda) [reply test/e2e/installplan_e2e_test.go:3198]: Yes, that's right.  I'll add nil check for fetchedInstallPaln.  Thanks!

File: test/e2e/installplan_e2e_test.go (hunk 2 above)
Comment (akihikokuroda) [reply test/e2e/installplan_e2e_test.go:3208]: Yes, I feel a minute is a little short now.  I'll change it to 5.

**Review by awgreene — APPROVED** [review]
Thanks, nice work on this!

File: test/e2e/installplan_e2e_test.go [hunk 4]
```diff
@@ -3192,14 +3192,20 @@ var _ = Describe("Install Plan", func() {
...
+			Eventually(func() bool {
+				fetchedInstallPlan, err := fetchInstallPlanWithNamespace(GinkgoT(), crc, installPlanName, ns.GetName(), buildInstallPlanPhaseCheckFunc(operatorsv1alpha1.InstallPlanPhaseInstalling))
+				if err != nil || fetchedInstallPlan == nil{
+					return false
+				}
+				if fetchedInstallPlan.Status.Phase != operatorsv1alpha1.InstallPlanPhaseInstalling {
+					return false
+				}
+				return hasCondition(fetchedInstallPlan, cond)
+			}, 5*time.Minute, interval).Should(BeTrue())
```
Comment (timflannagan) [inline test/e2e/installplan_e2e_test.go:3208]: nit: technically we can drop `5*time.Minute` call as it's the global default (and `interval` might also be the global default but I'm a bit fuzzier on that).

**Comment by timflannagan** [comment]
Force merging to try and clear out as many e2e flakes (that don't touch any runtime code) as much as possible.
