### PR TITLE
Fix flakey e2es

### LINKED ISSUE #3062: [FAIL] Install Plan [It] creation with permissions
```
 • [FAILED] [363.523 seconds]
Install Plan [It] creation with permissions
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2713

  Captured StdOut/StdErr Output >>
  waiting 103.588823ms for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - NO_CONNECTION
  waiting 701.742488ms for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - IDLE
  waiting 355.207008ms for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - CONNECTING
  waiting 598.533766ms for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - TRANSIENT_FAILURE
  waiting 2.399265723s for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - CONNECTING
  waiting 20.000601951s for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - TRANSIENT_FAILURE
  waiting 2.799121894s for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - CONNECTING
  waiting 20.000701415s for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - TRANSIENT_FAILURE
  waiting 4.600022137s for catalog pod install-plan-e2e-dhqvf/nginx-catalogvqw54 to be available (for sync) - READY
  probing catalog nginx-catalogvqw54 pod with address nginx-catalogvqw54.install-plan-e2e-dhqvf.svc:50051
  skipping health check
  Using the kubectl kubectl binary
  Using the artifacts/install-plan-e2e-dhqvf output directory
  Storing the test artifact output in the artifacts/install-plan-e2e-dhqvf directory
  Collecting get catalogsources -o yaml output...
  Collecting get subscriptions -o yaml output...
  Collecting get operatorgroups -o yaml output...
  Collecting get clusterserviceversions -o yaml output...
  Collecting get installplans -o yaml output...
  Collecting get pods -o wide output...
  Collecting get events --sort-by .lastTimestamp output...
  << Captured StdOut/StdErr Output

  Timeline >>
  created the install-plan-e2e-dhqvf testing namespace
  Creating catalog source nginx-catalogvqw54 in namespace install-plan-e2e-dhqvf...
  Catalog source nginx-catalogvqw54 created
  15:43:59.8797: subscription install-plan-e2e-dhqvf/sub-nginx-z8w8k state: UpgradePending (csv nginx8gxtk-stable): installPlanRef: &v1.ObjectReference{Kind:"InstallPlan", Namespace:"install-plan-e2e-dhqvf", Name:"install-qmrsp", UID:"b7adcb42-39d9-419f-9eac-d0a5f4413023", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"6300", FieldPath:""}
  waiting 996.565112ms for subscription install-plan-e2e-dhqvf/sub-nginx-z8w8k to have installplan ref: has ref &v1.ObjectReference{Kind:"InstallPlan", Namespace:"install-plan-e2e-dhqvf", Name:"install-qmrsp", UID:"b7adcb42-39d9-419f-9eac-d0a5f4413023", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"6300", FieldPath:""}
  waiting 201.020477ms for installplan install-plan-e2e-dhqvf/install-qmrsp to be phases [Failed Complete], in phase Installing
  waiting 4.00132768s for installplan install-plan-e2e-dhqvf/install-qmrsp to be phases [Failed Complete], in phase Complete
  {nginx8gxtk-stable ClusterServiceVersion }, {nginx8gxtk-stable Role }: true && false
  {nginx8gxtk-stable ClusterServiceVersion }, {nginx8gxtk-stable RoleBinding }: true && false
  {nginx8gxtk-stable ClusterServiceVersion }, {nginx8gxtk-stable ClusterRole }: true && false
  {nginx8gxtk-stable ClusterServiceVersion }, {nginx8gxtk-stable ClusterRoleBinding }: true && false
  {nginx8gxtk-stable ClusterServiceVersion }, {inskzmcf.cluster.com CustomResourceDefinition }: false && false
  {nginx8gxtk-stable ClusterServiceVersion }, {nginx-saphb6x ServiceAccount }: false && false
  {inskzmcf.cluster.com CustomResourceDefinition }, {nginx8gxtk-stable RoleBinding }: false && false
  {inskzmcf.cluster.com CustomResourceDefinition }, {nginx8gxtk-stable ClusterRole }: false && false
  {inskzmcf.cluster.com CustomResourceDefinition }, {nginx8gxtk-stable ClusterRoleBinding }: false && false
  {inskzmcf.cluster.com CustomResourceDefinition }, {nginx-saphb6x ServiceAccount }: false && false
  {inskzmcf.cluster.com CustomResourceDefinition }, {nginx8gxtk-stable Role }: false && false
  {nginx-saphb6x ServiceAccount }, {nginx8gxtk-stable ClusterRole }: false && false
  {nginx-saphb6x ServiceAccount }, {nginx8gxtk-stable ClusterRoleBinding }: false && false
  {nginx-saphb6x ServiceAccount }, {nginx8gxtk-stable Role }: false && false
  {nginx-saphb6x ServiceAccount }, {nginx8gxtk-stable RoleBinding }: false && false
  {nginx8gxtk-stable-nginx-saphb6x-64b44f4d58 Role }, {nginx8gxtk-stable RoleBinding }: true && false
  {nginx8gxtk-stable-nginx-saphb6x-64b44f4d58 Role }, {nginx8gxtk-stable ClusterRole }: true && false
  {nginx8gxtk-stable-nginx-saphb6x-64b44f4d58 Role }, {nginx8gxtk-stable ClusterRoleBinding }: true && false
  {nginx8gxtk-stable-nginx-saphb6x-64b44f4d58 RoleBinding }, {nginx8gxtk-stable ClusterRole }: true && false
  {nginx8gxtk-stable-nginx-saphb6x-64b44f4d58 RoleBinding }, {nginx8gxtk-stable ClusterRoleBinding }: true && false
  {nginx8gxtk-stable-764559f8f ClusterRole }, {nginx8gxtk-stable ClusterRoleBinding }: true && false
  Monitoring cluster role nginx8gxtk-stable-764559f8f
  Monitoring cluster role nginx8gxtk-stable-nginx-saphb6x-64b44f4d58
  Monitoring cluster role binding nginx8gxtk-stable-764559f8f
  Monitoring cluster role binding nginx8gxtk-stable-nginx-saphb6x-64b44f4d58
  Deleting CSV 'nginx8gxtk-stable' in namespace install-plan-e2e-dhqvf
  Deleting config map nginx-catalogvqw54-configmap...
  Deleting catalog source nginx-catalogvqw54...
  waiting for the catalog source nginx-catalogvqw54-2f4dm pod to be deleted...
  [FAILED] in [It] - /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2946 @ 10/11/23 15:49:07.155
  collecting the install-plan-e2e-dhqvf namespace artifacts as the 'creation with permissions' test case failed
  collecting logs in the ./artifacts/ artifacts directory
  tearing down the install-plan-e2e-dhqvf namespace
  resetting e2e kube client
  deleting install-plan-e2e-dhqvf/install-plan-e2e-dhqvf-operatorgroup
  deleting <global>/install-plan-e2e-dhqvf
  garbage collecting CRDs
  << Timeline

  [FAILED] 
  	Error Trace:	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2946
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
  	            				/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598
  	Error:      	Should be empty, but was map[nginx8gxtk-stable-764559f8f:{} nginx8gxtk-stable-nginx-saphb6x-64b44f4d58:{}]
  	Test:       	Install Plan creation with permissions
  	Messages:   	unexpected cluster role remain: map[nginx8gxtk-stable-764559f8f:{} nginx8gxtk-stable-nginx-saphb6x-64b44f4d58:{}]
  
  In [It] at: /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2946 @ 10/11/23 15:49:07.155

  Full Stack Trace
    github.com/stretchr/testify/assert.Emptyf({0x7ff48c3c7190, 0xc000ff4000}, {0x376f020, 0xc0020cbe60}, {0x3bfd3c2, 0x22}, {0xc001258eb0, 0x1, 0xc000400300?})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertion_format.go:64 +0x15f
    github.com/stretchr/testify/require.Emptyf({0x7ff48c3c7148, 0xc000ff4000}, {0x376f020, 0xc0020cbe60}, {0x3bfd3c2, 0x22}, {0xc001258eb0, 0x1, 0x1})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:145 +0xc5
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func16.13()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go:2946 +0x29d6
```

### LINKED ISSUE #3084: [FLAKE e2e (0)] ClusterServiceVersion AllNamespaces OperatorGroup [It] update deployment spec in an existing CSV for a hotfix
## Flaky Test Report

**Failure Log Link**
[Failure Log](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6747934047/job/18345167654#step:5:1253)
[Another Log](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6747102576/job/18342480313#step:5:1444)

**Relevant Failure Log**

```
------------------------------
• [FAILED] [307.357 seconds]
ClusterServiceVersion AllNamespaces OperatorGroup [It] update deployment spec in an existing CSV for a hotfix
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:3548

  Captured StdOut/StdErr Output >>
  customresourcedefinitions.apiextensions.k8s.io "inskxll8.cluster.com" not found
  Using the kubectl kubectl binary
  Using the artifacts/csv-e2e-hfxfw output directory
  Storing the test artifact output in the artifacts/csv-e2e-hfxfw directory
  Collecting get catalogsources -o yaml output...
  Collecting get subscriptions -o yaml output...
  Collecting get operatorgroups -o yaml output...
  Collecting get clusterserviceversions -o yaml output...
  Collecting get installplans -o yaml output...
  Collecting get pods -o wide output...
  No resources found in csv-e2e-hfxfw namespace.
  Collecting get events --sort-by .lastTimestamp output...
  << Captured StdOut/StdErr Output

  Timeline >>
  created the csv-e2e-hfxfw testing namespace
  waiting for CSV csv-e2e-hfxfw/csvsxlmt to reach condition
  waited 1.523814691s for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase  (): 
  waited 1.183447065s for csv csv-e2e-hfxfw/csvsxlmt - Pending (RequirementsUnknown): requirements not yet checked
  waited 1.078495851s for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase Pending (RequirementsUnknown): requirements not yet checked
  waited 197.309845ms for csv csv-e2e-hfxfw/csvsxlmt - InstallReady (AllRequirementsMet): all requirements found, attempting install
  waited 197.312409ms for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase InstallReady (AllRequirementsMet): all requirements found, attempting install
  waited 400.504354ms for csv csv-e2e-hfxfw/csvsxlmt - Installing (InstallSucceeded): waiting for install components to report healthy
  waited 400.50763ms for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase Installing (InstallSucceeded): waiting for install components to report healthy
  waited 400.541657ms for csv csv-e2e-hfxfw/csvsxlmt - Installing (InstallWaiting): installing: waiting for deployment dep-6nhv4 to become ready: deployment "dep-6nhv4" not available: Deployment does not have minimum availability.
  waited 400.547008ms for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase Installing (InstallWaiting): installing: waiting for deployment dep-6nhv4 to become ready: deployment "dep-6nhv4" not available: Deployment does not have minimum availability.
  waited 1.199216088s for csv csv-e2e-hfxfw/csvsxlmt - Succeeded (InstallSucceeded): install strategy completed with no errors
  waited 1.199215036s for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase Succeeded (InstallSucceeded): install strategy completed with no errors
  waiting for CSV csv-e2e-hfxfw/csvsxlmt to reach condition
  waited 197.59001ms for csv csv-e2e-hfxfw/csvsxlmt - Succeeded (InstallSucceeded): install strategy completed with no errors
  waiting for CSV csv-e2e-hfxfw/csvsxlmt to reach condition
  waited 196.814236ms for csv csv-e2e-hfxfw/csvsxlmt - InstallReady (ComponentUnhealthy): installing: deployment changed old hash=6d5557b98c, new hash=57b45f8885
  waited 601.52627ms for CSV csv-e2e-hfxfw/csvsxlmt: to be in phases [Succeeded], in phase InstallReady (ComponentUnhealthy): installing: deployment changed old hash=6d5557b98c, new hash=57b45f8885
  waited 400.006004ms for csv csv-e2e-hfxfw/csvsxlmt - Installing (InstallSucceeded): waiting for install components to report healthy
  waited 199.601382ms for csv csv-e2e-hfxfw/csvsxlmt - Installing (InstallWaiting): installing: waiting for deployment dep-6nhv4 to become ready: deployment "dep-6nhv4" waiting for 1 outdated replica(s) to be terminated
  waited 801.07288ms for csv csv-e2e-hfxfw/csvsxlmt - Succeeded (InstallSucceeded): install strategy completed with no errors
  [FAILED] in [It] - /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:3701 @ 11/03/23 16:52:15.895
  collecting the csv-e2e-hfxfw namespace artifacts as the 'update deployment spec in an existing CSV for a hotfix' test case failed
  collecting logs in the ./artifacts/ artifacts directory
  tearing down the csv-e2e-hfxfw namespace
  resetting e2e kube client
  deleting csv-e2e-hfxfw/csv-e2e-hfxfw-operatorgroup
  deleting <global>/csv-e2e-hfxfw
  garbage collecting CRDs
  << Timeline

  [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc0001ba130>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:3701 @ 11/03/23 16:52:15.895

  Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func7.4.25()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:3701 +0xf03
------------------------------
```

### LINKED ISSUE #3085: [FLAKE e2e (2)] Operator Group [It] e2e functionality
## Flaky Test Report

**Failure Log Link**
[Failure Log](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:574)

**Relevant Failure Log**
```
------------------------------
• [FAILED] [2.038 seconds]
Operator Group [It] e2e functionality
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:57

  Captured StdOut/StdErr Output >>
  E1103 17:27:56.158640   24870 runtime.go:79] Observed a panic: types.GinkgoError{Heading:"Your Test Panicked", Message:"When you, or your assertion library, calls Ginkgo's Fail(),\nGinkgo panics to prevent subsequent assertions from running.\n\nNormally Ginkgo rescues this panic so you shouldn't see it.\n\nHowever, if you make an assertion in a goroutine, Ginkgo can't capture the panic.\nTo circumvent this, you should call\n\n\tdefer GinkgoRecover()\n\nat the top of the goroutine that caused this panic.\n\nAlternatively, you may have made an assertion outside of a Ginkgo\nleaf node (e.g. in a container node or some out-of-band function) - please move your assertion to\nan appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).", DocLink:"mental-model-how-ginkgo-handles-failure", CodeLocation:types.CodeLocation{FileName:"/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go", LineNumber:141, FullStackTrace:"github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002[577](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:578)ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5\ngithub.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57\nk8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112\nk8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a\nk8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47\nk8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50\ngithub.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08", CustomMessage:""}} (Your Test Panicked
  require.ElementsMatch(GinkgoT(), expectedOperatorGroupStatus.Namespaces, fetched.Status.Namespaces, "have %#v", fetched.Status.Namespaces)
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141
    When you, or your assertion library, calls Ginkgo's Fail(),
    Ginkgo panics to prevent subsequent assertions from running.

    Normally Ginkgo rescues this panic so you shouldn't see it.

    However, if you make an assertion in a goroutine, Ginkgo can't capture the
    panic.
    To circumvent this, you should call

    	defer GinkgoRecover()

    at the top of the goroutine that caused this panic.

    Alternatively, you may have made an assertion outside of a Ginkgo
    leaf node (e.g. in a container node or some out-of-band function) - please
    move your assertion to
    an appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).

    Learn more at:
    http://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure
  )
  goroutine 1815 [running]:
  k8s.io/apimachinery/pkg/util/runtime.logPanic({0x39f2760?, 0xc000345b90})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
  k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
  panic({0x39f2760, 0xc000345b90})
  	/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/panic.go:884 +0x213
  github.com/onsi/ginkgo/v2.Fail({0xc000145600, 0x8a1}, {0xc00116df40?, 0x1?, 0x1?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/core_dsl.go:374 +0x225
  github.com/onsi/ginkgo/v2/internal/testingtproxy.(*ginkgoTestingTProxy).Errorf(0xc00124e120, {0x3bd1ba8?, 0xc00124e120?}, {0xc003ab3d50?, 0x38d0aa0?, 0xc00123c4b0?})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/testingtproxy/testing_t_proxy.go:88 +0x77
  github.com/stretchr/testify/assert.Fail({0x7faac0167c58, 0xc00124e120}, {0xc00127dc80, 0x165}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertions.go:333 +0x378
  github.com/stretchr/testify/assert.ElementsMatch({0x7faac0167c58, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertions.go:1057 +0x1c6
  github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5
  k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57
  k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112
  k8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a
  k8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47
  k8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50
  github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08
  github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x32612d616239342d, 0x65633034642d3436})
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463 +0x1b
  github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863 +0x98
  created by github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
  	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:850 +0xd65
  << Captured StdOut/StdErr Output

  Timeline >>
  created the operator-group-e2e-mv54q testing namespace
  17:27:55.7094: Creating CRD
  17:27:55.8229: Creating operator group
  17:27:55.9294: Waiting on operator group to have correct status
  [FAILED] in [It] - /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 @ 11/03/23 17:27:56.943
  cleaning up ephemeral test resources...
  deleting test subscriptions...
  deleting test installplans...
  deleting test catalogsources...
  deleting test crds...
  deleting test csvs...
  test resources deleted
  << Timeline

  [FAILED] 
  	Error Trace:	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
  	            				/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
  	            				/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/asm_amd64.s:1[598](https://github.com/operator-framework/operator-lifecycle-manager/actions/runs/6748278444/job/18346281275#step:5:599)
  	Error:      	elements differ
  	            	
  	            	extra elements in list A:
  	            	([]interface {}) (len=1) {
  	            	 (string) (len=36) "operator-group-e2e-mv54q-nrtpk-b2rjw"
  	            	}
  	            	
  	            	
  	            	listA:
  	            	([]string) (len=2) {
  	            	 (string) (len=30) "operator-group-e2e-mv54q-nrtpk",
  	            	 (string) (len=36) "operator-group-e2e-mv54q-nrtpk-b2rjw"
  	            	}
  	            	
  	            	
  	            	listB:
  	            	([]string) (len=1) {
  	            	 (string) (len=30) "operator-group-e2e-mv54q-nrtpk"
  	            	}
  	Test:       	Operator Group e2e functionality
  	Messages:   	have []string{"operator-group-e2e-mv54q-nrtpk"}
  
  In [It] at: /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 @ 11/03/23 17:27:56.943

  Full Stack Trace
    github.com/stretchr/testify/require.ElementsMatch({0x7faac0167c10, 0xc00124e120}, {0x35cd480, 0xc002577ec0}, {0x35cd480, 0xc002577ed8}, {0xc00123c680, 0x2, 0x2})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/require/require.go:102 +0xc5
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3.4()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:141 +0x1e5
    k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0xc002356301, 0x0})
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x1b
    k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x40ae870?, 0xc000128000?}, 0xc00123c7c8?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:154 +0x57
    k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x40ae870, 0xc000128000}, 0xc002af5278, 0x1b71a0a?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:207 +0x112
    k8s.io/apimachinery/pkg/util/wait.poll({0x40ae870, 0xc000128000}, 0x8?, 0x1b72745?, 0x345380f?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260 +0x9a
    k8s.io/apimachinery/pkg/util/wait.PollWithContext({0x40ae870, 0xc000128000}, 0x0?, 0xc00123c858?, 0x134c4c7?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85 +0x47
    k8s.io/apimachinery/pkg/util/wait.Poll(0x3c4eecd?, 0x30?, 0x0?)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:66 +0x50
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func20.3()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go:135 +0xd08
------------------------------
```

### PR DESCRIPTION
**Pull request by tmshort**
Fix #3062
Fix #3084 
Fix #3085 

Add cleanup in a loop

**Description of the change:**

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

File: test/e2e/installplan_e2e_test.go [hunk 1]
```diff
@@ -2869,92 +2869,127 @@ var _ = Describe("Install Plan", func() {
...
+					case <-time.After(pollDuration):
+						done <- struct{}{}
+						return
 					}
-				case <-time.After(pollDuration):
-					done <- struct{}{}
-					return
 				}
+			}()
+			err = crc.OperatorsV1alpha1().ClusterServiceVersions(generatedNamespace.GetName()).DeleteCollection(context.Background(), metav1.DeleteOptions{}, metav1.ListOptions{})
```
Comment (stevekuznetsov) [inline test/e2e/installplan_e2e_test.go:2962]: Without selectors on the ListOptions I don't think this call will do anything.

**Review by stevekuznetsov — COMMENTED** [review]
Is there a specific reason to use a watch here? There are a large number of reasons why a watch connection might be broken and handling re-instating the watch is a nontrivial amount of work. If there's no reason not to, I think we should simply do a poll and check for every object to be gone in the loop. 

Also - are any of those objects using a bona fide `OwnerReference`? I imagine the Cluster-scoped bits are not, but the SAs might, in which case this test is tantamount to a test of the k8s garbage collector, which I don't know is super useful.

File: test/e2e/installplan_e2e_test.go (hunk 1 above)
Comment (tmshort) [reply test/e2e/installplan_e2e_test.go:2962]: Hmmm... this is basically the same call as in the original code.

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go]: Which is probably why I added an explicit delete... AFAICT, it was a delete of all CSVs in the `generatedNamespace()`?

Comment (stevekuznetsov) [reply test/e2e/installplan_e2e_test.go]: Huh - you're right. No selector => every namespaced object. Wild. Rarely-used corner of the k8s API.

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go]: I removed it, so that I'm now targeting the specific CSV.

File: test/e2e/installplan_e2e_test.go [hunk 2]
```diff
@@ -2869,92 +2869,121 @@ var _ = Describe("Install Plan", func() {
...
 		}
 
+		createdResources["sa/"+serviceAccountName] = struct{}{}
+		GinkgoT().Logf("Monitoring service account %v", serviceAccountName)
+
 		crWatcher, err := c.KubernetesInterface().RbacV1().ClusterRoles().Watch(context.Background(), metav1.ListOptions{LabelSelector: fmt.Sprintf("%v=%v", ownerutil.OwnerKey, stableCSVName)})
 		require.NoError(GinkgoT(), err)
 		crbWatcher, err := c.KubernetesInterface().RbacV1().ClusterRoleBindings().Watch(context.Background(), metav1.ListOptions{LabelSelector: fmt.Sprintf("%v=%v", ownerutil.OwnerKey, stableCSVName)})
 		require.NoError(GinkgoT(), err)
+		saWatcher, err := c.KubernetesInterface().CoreV1().ServiceAccounts(generatedNamespace.GetName()).Watch(context.Background(), metav1.ListOptions{})
```
Comment (ncdc) [inline test/e2e/installplan_e2e_test.go:2894]: This would be a bigger change, but how would you feel about removing all these watches and replacing them with list calls inside of an eventually loop?

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go:2894]: Ambivalent. What are your thoughts here? Avoiding the watches (which should be more efficient) or the go routine?

Comment (ncdc) [reply test/e2e/installplan_e2e_test.go:2894]: I'd rather poll. Otherwise you have to deal with watches getting broken for various reasons, and restarting them.

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go:2894]: Let me look at it. There are five resources spread over three types, it won't be pretty!

Comment (tmshort) [reply test/e2e/installplan_e2e_test.go]: So, it might actually not be that bad...

File: test/e2e/installplan_e2e_test.go [hunk 3]
```diff
@@ -2869,92 +2867,42 @@ var _ = Describe("Install Plan", func() {
...
-						}
-					}
-				case <-time.After(pollDuration):
-					done <- struct{}{}
-					return
-				}
+		GinkgoT().Logf("deleting csv %s/%s", generatedNamespace.GetName(), stableCSVName)
+		Eventually(func() bool {
+			// Explicitly delete the CSV
+			err = crc.OperatorsV1alpha1().ClusterServiceVersions(generatedNamespace.GetName()).Delete(context.Background(), stableCSVName, metav1.DeleteOptions{})
```
Comment (ncdc) [inline test/e2e/installplan_e2e_test.go:2873]: Please move this before the Eventually loop - we only need to delete once

File: test/e2e/installplan_e2e_test.go [hunk 4]
```diff
@@ -2869,92 +2867,42 @@ var _ = Describe("Install Plan", func() {
...
-		case <-done:
-			break
-		case err := <-errExit:
-			GinkgoT().Fatal(err)
-		}
 
-		require.Emptyf(GinkgoT(), createdClusterRoleNames, "unexpected cluster role remain: %v", createdClusterRoleNames)
-		require.Emptyf(GinkgoT(), createdClusterRoleBindingNames, "unexpected cluster role binding remain: %v", createdClusterRoleBindingNames)
+			crbs, err := c.KubernetesInterface().RbacV1().ClusterRoleBindings().List(context.Background(), metav1.ListOptions{LabelSelector: fmt.Sprintf("%v=%v", ownerutil.OwnerKey, stableCSVName)})
+			if err != nil && !apierrors.IsNotFound(err) {
```
Comment (ncdc) [inline test/e2e/installplan_e2e_test.go:2881]: FYI, you only get a NotFound on a List call if the API itself doesn't exist.

File: test/e2e/installplan_e2e_test.go [hunk 5]
```diff
@@ -2869,92 +2867,42 @@ var _ = Describe("Install Plan", func() {
...
+			if len(crbs.Items) != 0 {
+				return false
+			}
 
-		Eventually(func() error {
-			_, err := c.GetServiceAccount(generatedNamespace.GetName(), serviceAccountName)
-			if err == nil {
-				return fmt.Errorf("The %v/%v ServiceAccount should have been deleted", generatedNamespace.GetName(), serviceAccountName)
+			crs, err := c.KubernetesInterface().RbacV1().ClusterRoles().List(context.Background(), metav1.ListOptions{LabelSelector: fmt.Sprintf("%v=%v", ownerutil.OwnerKey, stableCSVName)})
+			if err != nil && !apierrors.IsNotFound(err) {
```
Comment (ncdc) [inline test/e2e/installplan_e2e_test.go:2890]: FYI, you only get a NotFound on a List call if the API itself doesn't exist.

**Comment by tmshort** [comment]
The watches have been removed at the suggestion of @ncdc; I don't know if there are proper `ownerReferences`.

**Review by stevekuznetsov — DISMISSED** [review]

**Comment by ncdc** [comment]
@tmshort please make sure we have an issue for the most recent test flake - thanks!

**Comment by tmshort** [comment]
> @tmshort please make sure we have an issue for the most recent test flake - thanks!

See #3084

**Comment by ncdc** [comment]
Fantastic, thanks!

**Comment by ncdc** [comment]
@tmshort at this point, it's time to triage the test flake. This PR has hit it twice in a row. Please let me know if you would like help. Thanks!

**Comment by tmshort** [comment]
And #3085

**Comment by tmshort** [comment]
> @tmshort at this point, it's time to triage the test flake. ~This PR has hit it twice in a row~ EDIT: my bad, I look at e2e 0, not e2e 2. Please let me know if you would like help. Thanks!

There are two different problems... but I agree, they should be looked at!

**Comment by tmshort** [comment]
This should now fix #3085

File: test/e2e/operator_groups_e2e_test.go [hunk 6]
```diff
@@ -127,21 +127,30 @@ var _ = Describe("Operator Group", func() {
 		}
 		_, err = crc.OperatorsV1().OperatorGroups(opGroupNamespace).Create(context.TODO(), &operatorGroup, metav1.CreateOptions{})
 		require.NoError(GinkgoT(), err)
-		expectedOperatorGroupStatus := v1.OperatorGroupStatus{
-			Namespaces: []string{opGroupNamespace, createdOtherNamespace.GetName()},
-		}
+
+		// fetched namespaces might be in any order
+		namespaces := map[string]bool{}
```
Comment (ncdc) [inline test/e2e/operator_groups_e2e_test.go:132]: If you use sets.Set[string], it makes comparisons easier

Comment (tmshort) [reply test/e2e/operator_groups_e2e_test.go:132]: This is a pretty simple use; not sure changing to `sets` will improve this.

Comment (stevekuznetsov) [reply test/e2e/operator_groups_e2e_test.go:132]: The SymmetricDifference helper is really useful specifically for the comparison you're making in this test to be clear on the diff. Not a big deal for N=2 but much more useful as the set gets larger.

As an aside it would also make the semantics clearer - what would it mean for an entry to be in the map but `false`?

Comment (tmshort) [reply test/e2e/operator_groups_e2e_test.go:132]: Given the quantity and the very isolated, localized use case, not sure it's worth making the change.

@stevekuznetsov, I know what you're saying, but again, not sure it matters here.

**Comment by tmshort** [comment]
Added fix for #3084

File: test/e2e/operator_groups_e2e_test.go (hunk 6 above)
Comment (stevekuznetsov) [reply test/e2e/operator_groups_e2e_test.go:132]: Sure, no worries - this is fine. I tend to think of it in the other way - we've got a great helpful library that gives you the exact output you want to show devs when the test fails, and using it is no trouble at all - why not? :)
